### ISSUE TITLE
59590 - [Newsroom] Common Modules - Global Footer - Footer links and Social Media Icons is not aligned on Tablet and Mobile View

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#101]
**Severity - 3 - Medium**

**Description of the issue:** When checking on Tablet and Mobile view, footer links and social media icons were not aligned.  This issue also exist upon validating on Browserstack - Ipad Air 5 (Safari), Samsung Galaxy Tab S8 (Chrome) and Samsung Galaxy Note 10+ (Chrome)

**Legacy page:**  
homepage - https://newsroom.accenture.com/
search page - https://newsroom.accenture.com/search.cfm

**Migrated page:**
homepage - https://main--accenture-newsroom--hlxsites.hlx.live/
search page - https://main--accenture-newsroom--hlxsites.hlx.live/search

**Steps:**

1. Access the Newsroom Legacy and Migrated page.
2. Verify elements  for Footer in both domains.
3. Validate both domains on browser, tablet and mobile view via inspect.

**Expected Result:**
**Tablet view**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/79243945-ba6a-45f8-a647-cb11155c09f3)
**Mobile view**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/d48b7905-2631-40ad-acbe-779ae3ef504f)

**Browserstack - Ipad Air 5 - Safari**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/9f9f9829-7438-4f02-b7c6-a4f6b862b732)
**Browserstack - Samsung Galaxy Tab S8 - Chrome**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/7816ecb9-7cbe-48e2-be13-49c440df08c4)
**Browserstack - Samsung Galaxy Note 10+ - Chrome**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/125ff1af-f5ce-4c72-bbba-ee61dbcf8334)

**Actual:**
**Tablet view**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e55f92ef-02b3-4e28-909c-995917217e3b)

**Mobile view**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/4f50102a-5b64-4e22-92f3-c1ddd0834b76)

**Browserstack - Ipad Air 5 - Safari**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0599cf85-c4d8-41d3-ae67-70c3b09e169d)

**Browserstack - Samsung Galaxy Tab S8 - Chrome**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/637b6e67-70ee-4b19-ad46-50825188bf2f)

**Browserstack - Samsung Galaxy Note 10+ - Chrome**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/6731dcf5-7684-4161-a02e-151faf6bb35c)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59590
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by zozo-j** [comment]
Duplicate issue from #91
