### ISSUE TITLE
59564 - [Newsroom] Common Modules - Global Footer - Secondary Footer links should not be highlighted when hovering and missing tooltips

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#102]
**Severity - 3 - Medium**

**Description of the issue:** When hovering on the secondary footer links, it should not be highlighted and tooltip is missing.

**Legacy page:**  
homepage - https://newsroom.accenture.com/
search page - https://newsroom.accenture.com/search.cfm

**Migrated page:**
homepage - https://main--accenture-newsroom--hlxsites.hlx.live/
search page - https://main--accenture-newsroom--hlxsites.hlx.live/search

**Steps:**

1. Access the Newsroom Legacy and Migrated page.
2. Verify elements  for Footer in both domains.
3. Hover on the Footer links to check user interactions.

**Expected Result:**
Secondary Footer links have tooltips and not highlighted when hovering.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/3ab53e47-bc8b-43a0-81c8-dfb17000d15b)

**Actual:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0a7deaf4-b3de-4972-81e3-7d9b0cfa7373)

Azdo link : https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59564
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by jjjaspher** [comment]
this is invalid, closing the bug.
