### ISSUE TITLE
73350 [Newsroom] Search- pagination shows more than 5 number when there are more results to display

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#108]
Priority: 3 - Medium

Steps to Reproduce:

1.Consider the legacy page: https://newsroom.accenture.com/search.cfm 
and Migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/search?q=
2.Search with keyword say" new" 
3.400+ results gets fetched with the above keyword in both migrated and legacy site

Expected Result:
As there are more results , the pagination should get displayed with 5 page numbers in the pagination with a set of 10 results 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/f20941d2-c9aa-4a0b-8be3-8991df6e7793)

Actual Result: We see more than 5-page numbers getting displayed.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/ddcd3dcc-ae25-48e6-b886-6748827e2d28)

AzDo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/73350/
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by jjjaspher** [comment]
needs to revisit

**Comment by ravkiran** [comment]
@jjjaspher to have the pagination consistent, I made this change. I understand this is not same as current production site, but can you please check with business if this change is ok (to have the same pagination numbers for home page listing, category page listing and search page listings)?

**Comment by jjjaspher** [comment]
@ravkiran I also raised the same, I think it's more logical to show or can access the last 2 page button when it has many pages.
As per discussion, business agreed to the current implementation. We can close this issue.
