### ISSUE TITLE
73344 - [Newsroom] Search-tooltip is missing on the search button

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#109]
**Severity - 3 - Medium**

**Steps to Reproduce:**

1. Consider the legacy page: https://newsroom.accenture.com/search.cfm 
and Migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/search?q=
2. hover on the search button CTA

**Expected Result:** On hover , search tool tip with a hand cursor/icon should be displayed
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/29a976d9-626c-4ce3-9b49-c73b6c0cff64)

**Actual Result:** Tooltip is missing in franklin migrated search CTA
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/54e25081-259e-4d52-97ce-0415005df8d1)

Azdo Link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/73344
CC: @ravkiran @raymond-h-dev @amol-anand

**Comment by ravkiran** [comment]
fixed in https://github.com/hlxsites/accenture-newsroom/pull/115
