### ISSUE TITLE
[Analytics][Newsroom] Incorrect link type and module name on secondary nav component

### ISSUE THREAD

**Issue by cylevaldez** [hlxsites/accenture-newsroom#124]
Priority: 2 - High

**Steps to Reproduce:**
1. Navigate to https://main--accenture-newsroom--hlxsites.hlx.live/
2. Click any primary nav link (Insights/ Services/ Industries/ Careers/ About Accenture) in the global header. 
3. Inspect any secondary nav component
![image](https://github.com/hlxsites/accenture-newsroom/assets/144980894/159463c7-93b8-4db2-ac9e-342858adc1dc)

**Expected Result:**
The following data attributes are expected to be found on the secondary nav links:

- data-analytics-link-type="nav/paginate"
- data-analytics-module-name="nws-secondary-nav"

**Actual Result:**
The following data attributes are found below. This applies for all the secondary navigation found under Insights, Services, Industries, Careers and About Accenture. 
- data-analytics-link-type="navigation"
- data-analytics-module-name="nws-primary-nav"

cc: @ravkiran @amol-anand

**Comment by ravkiran** [comment]
fixed in #192
