### ISSUE TITLE
67485- [Newsroom] Common Modules -News Posting Article-For the Ipad pro 12 Alignment for the right side component is not matching with the legacy page

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#129]
**Priority: 3 - Medium**

1.open both the below URL legacy and franklin one on the IPAD Pro 12

**Legacy newsroom page:**
https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
**Adobe Franklin migrated page:** 
https://main--accenture-newsroom--hlxsites.hlx.live/news/accenture-completes-acquisition-of-anser-advisory

**Actual:** Alignment for the right-side component is not matching withe the legacy page
**Expected**: it should match with the legacy page.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0533ce6b-c23f-42f9-a245-597f5aa2c47e)

Adzo link:
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by raymond-h-dev** [comment]
- [ ] Bug Fixing
- [ ] For Testing - Feature Branch
- [ ] For PR Merge Approval
- [ ] For Testing - Main Branch
- [ ] Done
