### ISSUE TITLE
84836 - [Newsroom] Common Modules -News Posting Article-Exported PDF links are not coming inline  for the franklin exported page.

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#133]
**Severity 3 - Medium**
**Steps to Reproduce: | Analysis & Proposed Solution: | Location of the Element:**

1.open both the below URL legacy and franklin one

**Sample Reference/s:
Legacy newsroom page:**
https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
**Adobe Franklin migrated page:** 
https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-anser-advisory

2. click on the down press release button on the right side.

3.Open the downloaded PDF file.

4.Observe on the article para the inline links are not coming in line they are little downwards

Actual: it is not coming inline

Expected: it should come inline not downwards

![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/898ea500-01e9-4972-bdc1-5620ae235a5c)
Azdo link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/84836
CC: @ravkiran  @amol-anand  @raymond-h-dev

**Comment by jjjaspher** [comment]
Reopening to revert the changes have made.

**Comment by amol-anand** [comment]
why revert the changes?

**Comment by jjjaspher** [comment]
Re-opening the issue, Please see context here https://github.com/hlxsites/accenture-newsroom/pull/154

**Comment by jjjaspher** [comment]
as per my investigation there's still an open issue from the jsPDF regarding to .html() rendering hyperlinks.
https://github.com/parallax/jsPDF/issues/3146
CC: @amol-anand @ravkiran @raymond-h-dev

**Comment by jjjaspher** [comment]
I'll set this bug unassigned for now, as this has a blocker using the jsPDF approach.

**Comment by amol-anand** [comment]
@jjjaspher do you know what they use today? we can use the same libraries if needed.

**Comment by amol-anand** [comment]
We can also use https://github.com/eKoopmans/html2pdf.js instead of jsPDF. Let me know if you want to take a crack at it. if not, assign it to me.

**Comment by jjjaspher** [comment]
Hi @amol-anand, I tried to implement the html2pdf. The hyperlink issue was resolved however there's a discrepancy on how it is being rendered compared to the legacy pdf.
I also encountered an issue where in the text was being cut on page break. I haven't found a solution yet. 

**Test page:**  https://html2pdf-testing--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-song-wins-dan-wieden-titanium-grand-prix-for-tuvalu-the-first-digital-nation
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/fdf353b4-2654-4987-a5d9-87deb71315c8)

**Test page:** https://html2pdf-testing--accenture-newsroom--hlxsites.hlx.page/news/2023/servicenow-nvidia-and-accenture-team-to-accelerate-generative-ai-adoption-for-enterprises
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/6d90cbb9-f68f-44c5-9c40-0fbf7481770d)


**Branch** - https://github.com/hlxsites/accenture-newsroom/blob/html2pdf-testing/blocks/aside/aside.js
**File changes** - https://github.com/hlxsites/accenture-newsroom/compare/main...html2pdf-testing

**Comment by amol-anand** [comment]
I'll take a look at this and find some solution this week.
