### ISSUE TITLE
86038 - [Newsroom] Common Modules - Content and Links - Unexpected tooltip

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#135]
**Priority: 3 - Medium**

St**eps to Reproduce:**
1. Navigate to migrated page: [https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-anser-advisory](https://main--accenture-newsroom--hlxsites.hlx.live/news/accenture-completes-acquisition-of-anser-advisory)
Legacy Page: https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
2. Hover on "first announce" on the second paragraph.
 Expected: Text is highlighted without a tooltip.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/d22c3aba-eb81-4bbc-a882-c086ec7d8477)

Actual: Text is highlighted and displays a tooltip.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/aca129a5-129b-4aea-b4ed-020aaf74b9df)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/86038
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by jjjaspher** [comment]
waiting for business approval

**Comment by ravkiran** [comment]
Having a tooltip will help with accessibility score, we recommend to keep this as-is

**Comment by amol-anand** [comment]
This is not a bug. it is an enhancement.
