### ISSUE TITLE
93437- [Newsroom] Common Modules -  Tags - Padding issue in mobile view

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#162]
**Priority: 3 - Medium**
**Description of the issue**: Paddingn issue in mobile view. In Legacy newsroom page it has no padding while in the Adobe Franklin Migrated page it has a 16 px padding on left, right and 64 px on top.

Steps to Reproduce: 
1. Open the url(s): 
 Adobe Franklin migrated page:
https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-collaborated-with-microsoft-to-transform-its-azure-supply-chain
Legacy newsroom page:
https://newsroom.accenture.com/news/accenture-collaborated-with-microsoft-to-transform-its-azure-supply-chain.htm
2. Check for the spacing left spacing for the Tags
**Expected Result:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/8ba1a498-b321-49c1-aee5-6564ef95c27c)

**Actual Result:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/9b94b673-fa7d-4667-a50a-c6020b1bef40)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/93437
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
fixed in https://github.com/hlxsites/accenture-newsroom/pull/164
