### ISSUE TITLE
67499 - [Newsroom] Common Modules -News Posting Article-No space is there above the share component on legacy page for iPhone 12 pro max

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#172]
**Severity - 3 - Medium**

1. Open both the below URL legacy and franklin one on the IPhone 12 pro max

Legacy newsroom page:
https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
Adobe Franklin migrated page: 
https://main--accenture-newsroom--hlxsites.hlx.live/news/accenture-completes-acquisition-of-anser-advisory

2.  Scroll down the last till share section on both the pages

**Actual** : there is no space above the share section on the legacy page but there is on franklin page

**Expected**: Space should be removed as per the legacy page.

![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/ab0667ea-a0fc-4272-9ca1-db8977ca6ca8)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/67499
cc; @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
@veejayricana can we close this issue? or is there a reason this is still open?
