### ISSUE TITLE
83191 - [Newsroom] Share_Download CTA shouldn't be displayed in the page

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#182]
**Severity - 3 - Medium**

Steps to reproduce:
1. Launch the legacy page:[Accenture Reports Strong Third-Quarter Fiscal 2023 Results | Accenture](https://newsroom.accenture.com/news/accenture-reports-strong-third-quarter-fiscal-2023-results.htm)
Migrated page: [Accenture Reports Strong Third-Quarter Fiscal 2023 Results (main--accenture-newsroom--hlxsites.hlx.live)](https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-reports-strong-third-quarter-fiscal-2023-results)

Expected Result: The download press release CTA shouldn't be enabled/displayed in the above page as per the legacy site.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0dbf1d8a-7d40-4a04-b740-145e9d173c9e)

Actual Result: The CTA is displayed after the social media icons in the migrated page.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/bca69518-bcc3-4743-8676-f16b14e22f3c)
Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/83191
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by veejayricana** [comment]
Hi @ravkiran and @amol-anand  i will edit this document and add new row in metadata table for PDF toggle.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/60cda84e-b0c8-4c41-b2d1-25505bba8938)

sharepoint: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BF444EBC6-255B-4CC3-822D-A495BD695A35%7D&file=accenture-reports-strong-third-quarter-fiscal-2023-results.docx&action=default&mobileredirect=true

**Comment by amol-anand** [comment]
@veejayricana yes that will work. for other sites where we don't want the download pdf button to show, then we can add it and apply it across multiple paths in metadata.xlsx as well in a bulk fashion. closing this ticket.
