### ISSUE TITLE
100769 - [Newsroom] Newsfeed - Incorrect alignment for date range and calendar year filter in filter news section in extra small devices.

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#184]
**Severity - 3 - Medium**

**Steps to Reproduce:**

In the newsfeed, On clicking the arrow beside filter news the calendar year filter calendar alignment is incorrect in extra small devices.(iPhone se).
 

**Migrated page:** https://main--accenture-newsroom--hlxsites.hlx.live/subjects/analytics
**Legacy page:** https://newsroom.accenture.com/subjects/analytics

 

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/36bf4cef-510e-4e6e-8be8-8bcdf9635b80)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/74b5fcde-d448-456f-becf-faa3bb1ca20a)

Azdo link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/100769
CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by raymond-h-dev** [comment]
hi @jjjaspher @veejayricana @zozo-j  - can you verify with the team if this still a valid bug?
