### ISSUE TITLE
73369 - [Newsroom] Search_iOS_the search CTA button appears in oval shape rather than rectangle

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#186]
**Severity - 3 - Medium**

Steps to Reproduce:

1. Consider the legacy page: https://newsroom.accenture.com/search.cfm 
and Migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/search?q= in any of the iOS devices

Expected Result:
The design of the search cta button should be rectangular
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/1a84266b-a9de-48de-a815-f1c4e0e6266a)

Actual Result: We see the CTA button in oval shape as below.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0c73318c-007a-4df6-92aa-135d3b5b602f)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/73369
cc; @ravkiran @amol-anand @raymond-h-dev

**Comment by jjjaspher** [comment]
Unable to replicate, closing the bug now
