### ISSUE TITLE
Header overlapping - DE site

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/accenture-newsroom#193]
between 1000 to 1600px you can see some overlapping of elements in the header nav

https://main--accenture-newsroom-de--hlxsites.hlx.page/

open Branchen
![Screenshot 2023-09-26 at 3 17 50 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/3c844f06-22f5-4a86-829c-29ad551991d4)

**Comment by ravkiran** [comment]
working fine now
<img width="1081" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/9f57b9e4-8792-4fca-9ba2-4e60f8c396a9">
