### ISSUE TITLE
Additional Placeholders needed

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/accenture-newsroom#196]
**Calendar months and days**

![Screenshot 2023-09-26 at 10 47 07 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/c907c543-ea7e-4e19-8880-e8df1244dee8)

**Article date in Newslist card also needs to use local language for month**

![Screenshot 2023-09-26 at 10 46 26 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/feb51d90-5ccd-4ce3-ae9c-601bafed0d2a)

**Comment by amol-anand** [comment]
cc: @ravkiran

**Comment by amol-anand** [comment]
the dates in newslist cards are resolved by https://github.com/hlxsites/accenture-newsroom/pull/240

**Comment by ravkiran** [comment]
other styling issues are fixed in PRs 
https://github.com/hlxsites/accenture-newsroom/pull/285
https://github.com/hlxsites/accenture-newsroom/pull/287
