### ISSUE TITLE
123916 - [Newsroom] Common Modules - Content and Links - Table not displaying on preview/Franklin

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#200]
**Severity - 3 - Medium**

**Steps to Reproduce:**
1. **Navigate to migrated page:** https://main--accenture-newsroom--hlxsites.hlx.page/news/2000/9-out-10-online-holiday-shoppers-experiencedproblems-but-still-rated-web-better-than-stores-and-catalogs-for-purchasesaccording-to-new-accenture-study
Legacy Page:https://newsroom.accenture.com/news/9-out-10-online-holiday-shoppers-experiencedproblems-but-still-rated-web-better-than-stores-and-catalogs-for-purchasesaccording-to-new-accenture-study.htm
2. **Scroll down to table** - "Top 10 Problems Experienced % Internet Buyers".
**Expected**: The table rendered properly.
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/5d03ff0e-d939-453f-a9fb-74de33140f67)

**Actual:** Table is not rendered properly.

![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/f7c24c4a-60ea-4c6e-b03c-928b033d5fd8)

Authoring:

![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/9b799d12-5b3b-4134-8b6d-456b6066a2a3)
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/0ad1f5aa-2813-4ad7-9666-f1d912ce5883)

Azdo-link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/123916
CC: @ravkiran  @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Fixed in import script. next import should fix any issues with tables. attaching branch to this ticket

**Comment by amol-anand** [comment]
Keeping this open until we do one more import.
