### ISSUE TITLE
123729 - [Newsroom] Error Page - Content of the page is not translated and incorrect content

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#201]
**Severity - 3 - Medium**

**Steps to Reproduce:** 

In the migrated translated Error Page, content is not translated with respect to the language. Incorrect CTA text.

**Migrated page:** https://main--accenture-newsroom-de--hlxsites.hlx.live/test123

**Legacy page:** https://newsroom.accenture.de/test123

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/5f87ade8-7f01-40ae-8e0d-912625150323)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/cbc718d5-da76-453a-9a97-37b502816332)

Azdo-link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/123729
CC: @ravkiran @amol-anand  @raymond-h-dev

**Comment by amol-anand** [comment]
ES is not ready yet for review :)

**Comment by ravkiran** [comment]
@raymond-h-dev please update the keys in de placeholders.xlsx

**Comment by amol-anand** [comment]
can this be closed? @veejayricana

**Comment by veejayricana** [comment]
Hi @amol-anand and @ravkiran I already update the placeholder for de but still text is not translated to its specific translation.

**Comment by ravkiran** [comment]
@veejayricana this needs some code change, as 404 page may not be using the placeholders in all the places, I'll check this shortly.
