### ISSUE TITLE
123708 - [Newsroom] Error Page - Content of the page is different

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#202]
**Severity - 3 - Medium**

**Steps to Reproduce:**
In the Error page, the content is totally different. Please check the snippets below.

Migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/test123

Legacy page: https://newsroom.accenture.com/test123

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/7c6fe838-916b-4b56-921e-ab4f9cd04546)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/476c2c1b-dc9d-4d97-b070-deae158eaf81)

Azdo Link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/123708
CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by jjjaspher** [comment]
As per discussion with Eula and business,
the only requirements will be update the error message and retain the current UI. 
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/2a23365f-061e-4316-9df9-ba48af607d8c)
CC: @raymond-h-dev

**Comment by ravkiran** [comment]
@jjjaspher 
```
The page you are trying to access has been moved or renamed.
```
Sounds like the page was there before, but that may not be true. When we're moving to franklin, all the existing site urls will automatically be redirected to updated urls, so there shouldn't be any old site urls that'll give 404. 
404 may also occur when user type a wrong url as well. But its up to you, if you want to use this message.

Business can update the message in placeholders.xlsx
BTW, if you're adding the search link in this PNF page, please remember that this will be added in all the languages as well, so you may want to update the message there as well.

**Comment by amol-anand** [comment]
Since you can update the message in the placeholders.xlsx i'm going to close this issue.
