### ISSUE TITLE
131589 - [Newsroom] Unable to access AEM Franklin on both Chrome and Edge

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#204]
**Severity 2 - High**

**Description of the issue: Some ATCP resources has intermittent access on AEM Franklin/Sidekick**

List of users:
jennifer.z.abalos
michelle.magtanong
jessery.estamina

Screenshot of issue:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/bea7217d-f356-49fd-ba09-ffbb4ea1f0ae)

![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/1c5f5712-b193-4515-a8d7-2a6185cf42aa)

Azdo link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/131589https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/131589
CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by jjjaspher** [comment]
@ravkiran  @amol-anand  I experienced the same while developing
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/bbd2e68d-e494-4794-8d0a-0ce02028f623)
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/085a3353-4cf5-40de-a899-a981184c12e7)
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/dc57f172-7b7e-4d8a-8706-9f8fc4f36bb4)

**Comment by amol-anand** [comment]
There was an issue with DNS resolutions. https://status.hlx.live/ has more details on what happened. should be back to normal now afaik.

**Comment by amol-anand** [comment]
Changing the DNS provider to 1.1.1.1 (Cloudflare) or 8.8.8.8 (Google) provided an effective workaround.

**Comment by veejayricana** [comment]
As per Santos, Jayka Janelle (Scrum Master), I set this bug to close. All the said user above is can now access the franklin.

cc: @jjjaspher @amol-anand @ravkiran @raymond-h-dev
