### ISSUE TITLE
148548 - [HIGH] [Newsroom][Site Features and Functionality] - News Posting - Tags(de, br, es, fr, it, uk, sg) - PNF when Subject and Industries tags has been access

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#222]
Se**verity - 2 - HIGH**

Description of the issue: Page is not found when access via Subject and Industries tags

Steps to Reproduce: 
1. Open the url(s) and click used tag of the Subject Tag and Industries Tag.
(de) -  https://main--accenture-newsroom-de--hlxsites.hlx.page/de/news/2020/accenture-studie-zeigt-cloud-migrationen-k-c3-b6nnen-fast-60-millionen-tonnen-co2-emissionen-pro-jahr-reduzieren
(br) - https://main--accenture-newsroom-br--hlxsites.hlx.page/br/news/2020/tecnologia-imersiva-aumenta-confian-c3-a7a-dos-consumidores-e-vira-aliada-das-compras-online-revela-estudo-da-accenture-interactive
(es) - https://main--accenture-newsroom-es--hlxsites.hlx.page/es/news/50-consumidores-comportamientos-valores-no-son-los-mismos-tras-la-pandemia
(fr) - https://main--accenture-newsroom-fr--hlxsites.hlx.page/fr/news/2020/accenture-annonce-son-intention-acqu-c3-a9rir-opusline-et-la-cr-c3-a9ation-d-une-entit-c3-a9-d-c3-a9di-c3-a9e-au-secteur-de-la-sant-c3-a9-en-france
(it) - https://main--accenture-newsroom-it--hlxsites.hlx.page/it/news/2021/accenture-e-salesforce-espandono-la-loro-partnership-per-aiutare-le-aziende-rendere-il-proprio-business-sempre-pi-c3-b9-sostenibile
(uk) - https://main--accenture-newsroom-uk--hlxsites.hlx.page/english-uk/news/2022/accenture-acquires-carbon-intelligence
(sg) - https://main--accenture-newsroom-sg--hlxsites.hlx.page/english/news/2020/accenture-opens-innovation-hub-in-pune

NOTE: All pages of every geos listed are affected.
Root cause:  Incorrect/incomplete URL address. Geo folder is missing in the linked tags.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/a215922e-4a06-47a5-9b3c-65281d4c4b03)

Expected Result:
Industries Tag:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/efefd005-9039-40ef-908a-02f342e4b3b0)

Subject Tag:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/194e84ee-1892-46d7-b03c-722aa4c0bd13)

URL Format (Hover on any used tag under the Industries Tag and Subject Tag):
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/7e6f4d3e-164e-4def-b2d5-7012a3ceb6f8)

Actual Result:
Industries Tag:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e40bb721-c647-4cb2-828b-29a6c585cd84)

Subject Tag:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/6a7f9772-4d54-4ec1-973c-b74bec0dd00e)

URL Format (Hover on any used tag under the Industries Tag and Subject Tag):
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/9a5cf5f6-3210-4181-837b-eaa0cf5d452a)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/148548
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Yes this is an issue. news/cloud are not in the current sitemap for DE for example under subject/industries.. that's why those pages were not imported.

Can we get a full list of all pages / tags under subject/industries for all the geo sites so we can import more of them?

**Comment by amol-anand** [comment]
One other thing we can do is to have ONE subject and ONE industry page and just pass in the value as a url param. then the newslist category page will just get the value form the url parameter and use that instead of the block in the page itself. that way, no matter what tags they add, they don't need to create a new subject/industry page. this would be easier for the authors too.

@ravkiran thoughts?

**Comment by veejayricana** [comment]
Sorry for the late update:

I alredy create a code fix for this one @amol-anand and @ravkiran. Here is the flow of my code.
Flow of my code.
1. Check if the link has as country code in link, especially in non-us.
2. Check if there is available translation in placeholder excel for the subject/industry.
3. Getting the proper file name by checking if its translate in placeholder but if its not im placing placing the cleanupvalue that you create in the code.
4. In some non-us if the cleanupvalue/translation is equal to news, it will automatically remove the subject/industry folder in the path (for de and fr )

**Comment by veejayricana** [comment]
Hi @ravkiran and @amol-anand,

Reopening this issue due to pages under subject and industry is still PNF in local geo that said above except for jp and us.

**Root cause analysis:**
1. In local geo link path under subject/industry tagging has country path sample : /de/subjects
2. In local geo link path under subject/industry tagging has been translate to country language translation. sample : /it/argomento/interactive-marketing/
3. In local geo link path under subject/industry tagging document file name has been translate to country language. sample Tecnología (https://newsroom.accenture.es/es/subjects/technology/)

This issue has also been tested and verify the QA that still not fix.

cc: @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana for the pages to work, we still have to re-import the pages, but the code changes required are done. Re-import we'll be doing on Monday (10/09) and then will update the placeholders with all the translations, then this will be fixed. But that's not code change, only content change. You can keep this ticket open and validate after re-import is done.

**Comment by Jaykaaa** [comment]
Hello @ravkiran  Do we have an update on the re-import? Is it done? Thanks

**Comment by amol-anand** [comment]
yes re import was done yesterday night as per my updates on the slack channel

**Comment by ravkiran** [comment]
Even though the import is done, we're having a bit of issue with query-index not updating the old industries/subjects values, so we need to delete that and re-index. Will update you when the query index issue is fixed.

**Comment by Jaykaaa** [comment]
hello @ravkiran  do we have an update on this? Thanks

**Comment by ravkiran** [comment]
query index issues are fixed.
the above pages are not existing any more, as we've fixed the paths to be more similar to accented characters rather than decoded names with `c3`, `a9` etc.
But there's an issue with the industries and subjects in sg, uk and fr. That's handled in https://github.com/hlxsites/accenture-newsroom/pull/329

Now this issue should be fixed.

**Comment by ravkiran** [comment]
Looks like fr will still not work, waiting for https://main--accenture-newsroom-fr--hlxsites.hlx.live/query-index.json?offset=0&limit=255&sheet=articles to be cleared. Will update here once fr works.

**Comment by ravkiran** [comment]
fr query-index cache issue is fixed, all the industries/subjects page should be working.
fr example: https://tempnewsroom.accenture.fr/fr/sujet/cloud

**Comment by Jaykaaa** [comment]
Thank you @ravkiran

**Comment by veejayricana** [comment]
Hi @ravkiran and @amol-anand reopening this bug: 
Concern :  In local geo IT subject is still PNF.
Note : subject is translated to argomento
sample page : https://tempnewsroom.accenture.it/it/news/2022/accenture-technology-vision-2022-il-continuum-del-metaverso

**Comment by amol-anand** [comment]
const validCategoryPages = ['/industries/', '/secteurs-dactivit/', '/subjects/', '/sujet/', '/argomento/'];
FR - /secteurs-dactivit/ (industries) and /sujet/ (subject)
IT - /argomento/ (subject)

since all other languages have industries and subjects for the category pages, we might want to just convert these also to use industries and subjects to be consistent. will that be okay?
