### ISSUE TITLE
[Analytics][Newsroom] Content Security Policy Issue for tempnewsroom.accenture.com

### ISSUE THREAD

**Issue by cylevaldez** [hlxsites/accenture-newsroom#223]
Priority: 1 - Critical

**Steps to Reproduce:**
1. Navigate to any of the tempnewsroom domains 
https://tempnewsroom.accenture.com
https://tempnewsroom.accenture.jp/
https://tempnewsroom.accenture.de/
https://tempnewsroom.accenture.fr/
https://tempnewsroom.accenture.it/
https://tempnewsroom.accenture.es/
https://tempnewsroom.accenture.co.uk/
https://tempnewsroom.accenture.sg/
https://tempnewsroom.accenture.pt/
https://tempnewsroom.accenturebr.com
2. Check console errors

**Expected Result:** 
No content security policy error is displayed

**Actual Result:** 
Content security policy errors are found
![image](https://github.com/hlxsites/accenture-newsroom/assets/144980894/e2aa2ed6-141f-4ad8-a091-1d5000cedb7c)

cc: @ravkiran @amol-anand

**Comment by amol-anand** [comment]
@raymond-h-dev yes, I've assigned it to myself
