### ISSUE TITLE
149585 - [High] [Newsroom] Newsfeed- Newsfeed section is not visible for local geos [it, fr, sg, es, jp, pt]

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#224]
**Severity - 2 - HIGH**

Steps to Reproduce: 
1. Open URL migrated and legacy newsroom page for local geo  [it, fr, sg, es, jp, pt]
**Actual:**  Newsfeed section missing
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/d73068d0-2e34-4d68-ac1d-c788db0152bc)

**Expected:** Newsfeed section should be visible
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e8b97891-90f8-48a3-8427-b49045f1c171)

Migrated pages:
https://main--accenture-newsroom-de--hlxsites.hlx.live/
https://main--accenture-newsroom-it--hlxsites.hlx.live/
https://main--accenture-newsroom-jp--hlxsites.hlx.live/
https://main--accenture-newsroom-fr--hlxsites.hlx.live/
https://main--accenture-newsroom-es--hlxsites.hlx.live/

Legacy Newsroom pages:
https://newsroom.accenture.jp/
https://newsroom.accenture.de/
https://newsroom.accenture.it/
https://newsroom.accenture.es/

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/149585
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
@veejayricana can you please clear your browser cache and check again. i do see the newsfeed in all those links. see screenshot below
![Screenshot 2023-09-30 at 5 29 53 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/cc506449-12ef-4c9c-9c53-9309c579a355)

**Comment by jjjaspher** [comment]
Hi @amol-anand, in some geo, upon pulling news cards there are cases that "matchingParagraph" doesn't have value for the reason that removing of first "br" element  (which I recently added) throw a console error. Adding a null check will fix the issue. Please review my code update here, Thank you!
https://github.com/hlxsites/accenture-newsroom/pull/231
