### ISSUE TITLE
[Analytics][Newsroom] Missing variables event1 and evar89 upon clicking download button

### ISSUE THREAD

**Issue by cylevaldez** [hlxsites/accenture-newsroom#233]
Priority: 2 - High

**Steps to Reproduce**
1. Navigate to any article with a download button (i.e. https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-anser-advisory)
2. Click the download button

**Expected Result**
event1 and evar89 are triggered

**Actual Result**
event1 and evar89 are not triggered

**Resolution:** 
Missing href attribute inside a tag element. Implement and add href attirute inside the a tag like the one existing on the Legacy Page. See screenshot below. 

Legacy Page:
![image](https://github.com/hlxsites/accenture-newsroom/assets/144980894/f7d4d666-a6d4-4d04-9428-0121bd0eeadf)

Migrated Page: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/144980894/1ca170d8-ec18-40e5-8e68-f14273c3b70a)

**Comment by ravkiran** [comment]
add `data-file-name` attribute with the file name that'll be downloaded, so that the analytics can collect this data.
Reyes - will provide the id/class to use on `a` tag and update the analytics to collect the data accordingly.

**Comment by ravkiran** [comment]
@cylevaldez 

adding `data-analytics-download-filename="Accenture-Completes-Acquisition-of-Anser-Advisory.tekpdf"`

<img width="1350" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/da2071da-542e-4087-80a1-3466e3764de0">
