### ISSUE TITLE
162716 - [HIGH] [Newsroom] [ External Search] - Sitemap - Incorrect URL naming in sitemap

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#243]
**Severity 2 - High**

Description of the issue: Incorrect url naming for the sitemap index
**Expected:** Legacy pa
/sitemapindex.xml
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/b50585e9-4224-450a-a869-e1ff91f4bb8c)

**Actual:** Migrated page
/sitemap.xml
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/8c570517-e8d0-4006-ae2e-f42ac35820b4)

Azdo link  - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/162716
CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
There is a difference between a sitemap index and a sitemap as discussed on slack. They serve two different purposes. We can add a sitemap index if necessary. whatever the robots.txt points to is what would get used. This is not a bug.

**Comment by amol-anand** [comment]
yes, currently it is /sitemap.xml, so no change would be needed?

**Comment by jjjaspher** [comment]
as per Eula she is referring to the robots.txt, Right now this is the value when we tried to access the /robots.txt
https://main--accenture-newsroom--hlxsites.hlx.live/robots.txt
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/f7cacbd6-50b0-44d9-b6a9-078bfa24ea13)

I think she just want to ensure that the sitemap value on the robots.txt is "sitemap.xml" as well

**Comment by ravkiran** [comment]
@jjjaspher since we're still validating, we've not updated the sitemap url in this. But once we're ready, this should be updated to have the sitemap url with `sitemap.xml`

**Comment by amol-anand** [comment]
we won't update robots.txt until just before go-live. I'll keep this ticket open and mark it with a Go-Live label

**Comment by amol-anand** [comment]
complete as per #408
