### ISSUE TITLE
161646 [Newsroom] [High] Vulnerable to CSS Injection

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#248]
Priority: 2 - High
Category: Injection

Description: The application does not perform input validation and accepts CSS code as an input. A user can execute scripts in the application. Attackers can inject and perform unwanted actions towards the system. We have seen the CSS injection in the application.

Impact: Able to inject arbitrary CSS into the application which may enable various attacks, including:

• Executing arbitrary JavaScript using IE's expression () function.
• Using CSS selectors to read parts of the HTML source, which may include sensitive data such as anti-CSRF tokens.
• Capturing any sensitive data within the URL query string by making a further style sheet import to a URL on the attacker's domain and monitoring the incoming Referrer header.

Remediation Recommendation: Ensure that user input is adequately escaped before embedding it in CSS blocks and consider using a whitelist to prevent loading of arbitrary style sheets.

Affected URL:
[https://tempnewsroom.accenture.com/search?q=%3Cstyle%3E*%7Bcolor%3Ared%7D%3C%2fstyle%3E](https://tempnewsroom.accenture.com/search?q=%3cstyle%3e%2a%7bcolor:red%7d%3c%2fstyle%3e)
[https://tempnewsroom.accenture.com/search?q=%3Cstyle%3E*%7Bcolor%3Agreen%7D%3C%2fstyle%3E](https://tempnewsroom.accenture.com/search?q=%3cstyle%3e%2a%7bcolor:green%7d%3c%2fstyle%3e)

Evidences:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/fae41aa0-53ff-4876-893e-ea5c5823997c)

![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/fae41aa0-53ff-4876-893e-ea5c5823997c)

AzDo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/161646/
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by raymond-h-dev** [comment]
@zozo-j @amol-anand  - i already fixed this issue; see PR #226
