### ISSUE TITLE
161626 [Newsroom] [High] Reflected Cross Site Scripting (XSS)

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#249]
Priority: 2 - High
Category: Injection

Description: The application does not perform input validation and accepts the scripts and characters as an input. A user can execute malicious scripts in the application.

Impact: This may allow attackers to execute scripts in the victim’s browser which can disclose data, deface web sites, or redirect the user to malicious sites.

Remediation Recommendation: Validate the application input at the server-side for length, type, and business rules before accepting any data to be stored or processed. Encode/escape the user-supplied data appropriately before rendering to the browser.

Affected URL:
[https://tempnewsroom.accenture.com/search?q=%3Chtml%3E+%3Ca+href%3D%23+onmouseover%3D%22alert(%27Hey.%20I%20got%20an%20vulnerbility%27)%22%3EThis+is+test+%3C%2fa](https://tempnewsroom.accenture.com/search?q=%3chtml%3e+%3ca+href%3D%23+onmouseover%3D%22alert%28%27Hey.%20I%20got%20an%20vulnerbility%27%29%22%3eThis+is+test+%3c%2fa) 
https://tempnewsroom.accenture.com/search?q=--%21%3e%3cimg+src%3D1+onerror%3Dalert%28%60XSS%60%29%3e

Evidences:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/2bb16282-9d9c-41a6-a63d-945431bd5ee9)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/4a041496-bbc7-4b69-b9c0-f32d4b1761a4)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/9c1e4557-8221-43be-a687-65252adc89e8)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/2e5a8f99-e3d4-4491-bc58-ae94e0008a62)

AzDo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/161626/

cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
@jjjaspher didn't you already fix this one?

**Comment by raymond-h-dev** [comment]
@zozo-j @amol-anand  - i already fixed this issue; see PR #226
