### ISSUE TITLE
[Analytics][Newsroom] Incorrect value of link type (prop35) in the hero title link

### ISSUE THREAD

**Issue by cylevaldez** [hlxsites/accenture-newsroom#253]
Priority: 4 - Low

**Steps to Reproduce:**
1. Navigate to https://main--accenture-newsroom--hlxsites.hlx.live/
2. Click the "Accenture Reports Strong Third-Quarter Fiscal 2023 Results" in the marquee/hero component

**Expected Result:** 
data-analytics-link-type = hero content

**Actual Result:**
data-analytics-link-type = engagement

**Comment by ravkiran** [comment]
@cylevaldez I see different link types. For the Read More, I'm seeing `engagement` and for the h2, I see `hero content`
What's the logic here? For the read more, should it be `engagement` and remaining links in this area should be `hero content` ?
<img width="1331" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/21c56831-5c36-4189-985a-1ef71f152bf0">

**Comment by ravkiran** [comment]
After discussing with Jonah in today's call, all the links in hero overlay should be `hero content`, no need to have the `engagement` for Read More CTA.
