### ISSUE TITLE
175623 - [High] [Newsroom] Not able to publish using Sidekick

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#255]
**Severity - 2 High**

This bug is logged as we cannot publish in Franklin using sidekick. There is no toolbar displayed as seen in screenshot below.

**Azdo** link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/175623
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
@veejayricana as discussed in the slack channel, this won't work until we release a new sidekick. should be resolved shortly

**Comment by amol-anand** [comment]
We released a new sidekick on Friday. This should work now.

**Comment by ravkiran** [comment]
@veejayricana if you download the latest sidekick, this is fixed.

**Comment by veejayricana** [comment]
Hi @amol-anand and @ravkiran, reopening this issue as still we are encountering issue in the new update sidekick.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/33d4ac95-5ca6-457d-88d4-e781746c6b93)

**Comment by amol-anand** [comment]
Fix for Scenario 2 should be coming tomorrow.

For Scenario 1 - you can add a project to the sidekick only from either the github url to the project OR from the main--*.hlx.page/live url of the project.

**Comment by amol-anand** [comment]
This should be fixed now

**Comment by Jaykaaa** [comment]
Hello. As discussed in our call and in slack, we need the RCA for this issue. Thanks.

**Comment by tripodsan** [comment]
we were still rolling out the support for vanity domains for sharepoint, and some of the GEOs werent ready yet, when we switched the sharepoint

**Comment by Jaykaaa** [comment]
hi @tripodsan  is this the RCA for this issue?

**Comment by Jaykaaa** [comment]
Can you please provide details like
Why did the issue happen?
How can we prevent it from happening again?

**Comment by amol-anand** [comment]
RCA: we were still rolling out the support for vanity domains for sharepoint, and some of the GEOs werent ready yet, when we switched the sharepoint
