### ISSUE TITLE
175911 - [ASA] - robots.txt not implementation

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#261]
The application’s robots.txt is not available.  Accenture requires the implementation of a securely configured Robots.txt to prevent search engines from crawling directories that are not intended to for public use.

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/175911
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Completed as per #408
