### ISSUE TITLE
175914 - [ASA] - Non Standard ports open

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#263]
Check if the ports are open for valid purposes. Close the unsecure or unnecessary open ports.
Server hardening should be done as per Accenture policies/standards. https://in.accenture.com/protectingaccenture/infrastructure/infrastructure-security-standards/

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/175914
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Which ports are open? more details please.

**Comment by raymond-h-dev** [comment]
> Which ports are open? more details please.

this is more about the opened http port 80 
![image](https://github.com/hlxsites/accenture-newsroom/assets/44294653/33ac97e2-f9ab-48fa-b3c5-c34c8992909d)

**Comment by amol-anand** [comment]
HTTP to HTTPS redirect usually happens at the CDN level.

**Comment by ravkiran** [comment]
port 80 for http and 443 for https is open on all the servers that needs to serve the traffic, May I know what is the issue?
