### ISSUE TITLE
167654 - [Newsroom] Homepage - Secondary/Multi-Navigation - (UK, SG, PT, BR) - PNF Links

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#266]
Severity - 3 - Medium
**Steps to Reproduce:** 

**Navigate to migrated pages:**
https://main--accenture-newsroom-uk--hlxsites.hlx.live/
https://main--accenture-newsroom-sg--hlxsites.hlx.live/
https://main--accenture-newsroom-pt--hlxsites.hlx.live/
https://main--accenture-newsroom-br--hlxsites.hlx.live/

**Legacy Pages:**
https://newsroom.accenture.co.uk/
https://newsroom.accenture.sg/
https://newsroom.accenture.pt/
https://newsroom.accenturebr.com/

Click "Contact us", "Fact Sheet", "Earning Infographics" in Secondary/Multi-Navigation.
**Expected:** Links open pages when clicked.
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/15a12abe-c653-4d2a-90ad-b1200c2ed3a0)
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/5ac54464-119a-43b4-89a4-7c14dc837180)

**Actual:** Links directs to PNF

![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/8b589cf2-4e8e-4fda-914e-a2d5a1c64b9b)

Azdo Link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/167654
CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by jjjaspher** [comment]
Hi @ravkiran, I think this is similar to this issue https://github.com/hlxsites/accenture-newsroom/issues/131 which you resolved. 
Is the pages for the "Contact us", "Fact Sheet", "Earning Infographics" are already available for the said geos?

**Comment by ravkiran** [comment]
@jjjaspher 
sg, pt, br don't have the language specific "contact us", "Fact sheet" and "Earning infographics" pages, all these are pointing to global site (i.e., en). uk site is showing its own contact us, https://newsroom.accenture.co.uk/english-uk/pr-contacts/, but this is going to 404 and this is not part of sitemap. So, I'm thinking that this is a human error, they may want to point to the global site like others.

Given that all these should point to the global site, which is https://main--accenture-newsroom--hlxsites.hlx.page/ but these are using https://newsroom.accenture.com. @amol-anand is doing one last re-import for the language sites tomorrow, then he'll update these urls to point to Franklin global site, when we go live, this will point automatically to what ever CDN.

We can check back this ticket after the re-import is done and make any title changes for the links after the re-import is complete.

**Comment by jjjaspher** [comment]
> @jjjaspher sg, pt, br don't have the language specific "contact us", "Fact sheet" and "Earning infographics" pages, all these are pointing to global site (i.e., en). uk site is showing its own contact us, https://newsroom.accenture.co.uk/english-uk/pr-contacts/, but this is going to 404 and this is not part of sitemap. So, I'm thinking that this is a human error, they may want to point to the global site like others.
> 
> Given that all these should point to the global site, which is https://main--accenture-newsroom--hlxsites.hlx.page/ but these are using https://newsroom.accenture.com. @amol-anand is doing one last re-import for the language sites tomorrow, then he'll update these urls to point to Franklin global site, when we go live, this will point automatically to what ever CDN.
> 
> We can check back this ticket after the re-import is done and make any title changes for the links after the re-import is complete.

Hi @ravkiran got the clarification from Eula and we'll just repointing the link to the EN geo if there's no created page from the sharepoint. Thanks!

**Comment by jjjaspher** [comment]
Hi @ravkiran, if my understanding is correct, once the re-import is completed, all multinav links will be automatically pointed to its what ever CDN without updating the doc file? because I updated few links and point to EN link as per Eula's advise.
i.e 
from:  https://newsroom.accenture.co.uk/english-uk/pr-contacts/ 
to: https://main--accenture-newsroom--hlxsites.hlx.live/pr-contacts to 

Please let me know once the re-import is done and we'll recheck. Thank you.

**Comment by jjjaspher** [comment]
Hi @ravkiran, we've got an advise from Eula to redirect the links if it's PNF(or page is not created)
I tried to update some few links.
i.e 
from:  https://newsroom.accenture.co.uk/english-uk/pr-contacts/ 
to: https://main--accenture-newsroom--hlxsites.hlx.live/pr-contacts

but seems not working because it's automatically converted to UK domain. https://main--accenture-newsroom-uk--hlxsites.hlx.live/pr-contacts which I think it is related to what you're saying that _"this will point automatically to what ever CDN"_

I guess after re-import activity then all pages will be available including the multinav links?

Please let me know once the re-import is done and we'll recheck. Thank you.

**Comment by amol-anand** [comment]
Use the newsroom.accenture.com URL rather than main--accenture-newsroom--hlxsites URL and after go-live it will work fine.

**Comment by ravkiran** [comment]
@jjjaspher can you update the content in these lang sites to use newsroom.accenture.com instead of main--accenture-newsroom--hlxsites.live as per @amol-anand suggestion?

**Comment by jjjaspher** [comment]
Sure, @amol-anand @ravkiran. Thanks!

**Comment by amol-anand** [comment]
No, that should be it. closing the ticket now.
