### ISSUE TITLE
143532 - [Geo De jp fr it es sg][Newsroom] Common Modules - Hero-Font size for the title text is more on the franklin page.

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#270]
Priority: 3 - Medium

Steps to Reproduce: | Analysis & Proposed Solution: | Location of the Element:
1.open both the below URL legacy and franklin one

Legacy newsroom page:
https://newsroom.accenture.de/
Adobe Franklin migrated page: 
https://main--accenture-newsroom-de--hlxsites.hlx.page/

2.Check the font size for the article heading

Actual: The font size for the heading on hero is big in comparison to legacy page

Expected: It should match legacy

Franklin page

Image
Geos testing update
Note:
For jp: hero article heading is also bold on legacy which is not franklin page

For below geos not sure about the font size as there is no hero present for the legacy page.
co.uk
br
pt

AzDo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/143532/
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by zozo-j** [comment]
Waiting for business reply regarding  the inconsistencies in font sizes across en and other local geos.

**Comment by zozo-j** [comment]
Font size issue is still in question and waiting for business reply.

**Comment by amol-anand** [comment]
I would recommend having the same design across all the sites. They might have been built at different times. Having one design will give it a consistent look and feel.

**Comment by amol-anand** [comment]
closing this since we haven't heard from the business in 2 weeks about it. assuming this is not an issue anymore. if it is, please reopen.
