### ISSUE TITLE
143106 [Geo De][Newsroom] Common Modules - Hero-Newsroom heading alignment is not matching with the live site

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#272]
Priority: 3 - Medium

Steps to Reproduce: | Analysis & Proposed Solution: | Location of the Element:

1.open both the below URL legacy and franklin one

Legacy newsroom page:
https://newsroom.accenture.de/
Adobe Franklin migrated page: 
https://main--accenture-newsroom-de--hlxsites.hlx.page/

2.Verify the newsroom heading is not aligned with the legacy page

Legacy de page
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/619c581a-a1e4-4d0d-85a4-96c53b921664)

frankiln page
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/ecf227c4-9257-4350-ad86-cd2bb4617217)
Expected: It should be aligned as per the legacy page.

AzDo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/143106/

cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by zozo-j** [comment]
Font size issue is still in question and waiting for business reply.

**Comment by amol-anand** [comment]
Related issue: https://github.com/hlxsites/accenture-newsroom/issues/270

**Comment by amol-anand** [comment]
Closing this as we have not heard back from the business if this is still an issue. Design will be consistent (as it should) across all sites and not different.
