### ISSUE TITLE
182119 - [MVP][Newsroom] - Environments and Infrastructure - Repository readme.md file

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#273]
As a developer, I want to remove the environment of accenture newsroom links to our repository readme.md file for security purposes.
+ Remove the below under ## Environments
- Preview: https://main--accenture-newsroom--hlxsites.hlx.page/
- Live: https://main--accenture-newsroom--hlxsites.hlx.live/

<img width="505" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/142872664/df3c9854-c073-4c41-8534-18cba8273dd3">

**Comment by jjjaspher** [comment]
We'll revert it back once the repository is has been set to private.
CC: @raymond-h-dev

**Comment by raymond-h-dev** [comment]
@amol-anand can we merge this today as this will be part of todays plan?
