### ISSUE TITLE
[Analytics][Newsroom] Incorrect value for data-analytics-link-name for content cards

### ISSUE THREAD

**Issue by cylevaldez** [hlxsites/accenture-newsroom#292]
Priority: 2-Medium

**Steps to Reproduce:**
1. Navigate to https://tempnewsroom.accenture.com/
2. Inspect any "read more" link in the content cards
![image](https://github.com/hlxsites/accenture-newsroom/assets/144980894/87c211ff-508f-4272-95d5-2f16454f14c4)

**Expected Result:** 
data-analytics-link-name="read more: <title of the card>"
![image](https://github.com/hlxsites/accenture-newsroom/assets/144980894/dc09e648-fd0c-4bc9-a641-d504af109ef9)

**Actual Result:** 
data-analytics-link-name="read more"

**Comment by ravkiran** [comment]
@cylevaldez I don't see this article in the listing in https://tempnewsroom.accenture.com/

<img width="1488" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/56124b04-95bb-47e3-909b-9930a0d0bba2">

and on the existing articles, I do see the Read More link name as `READ MORE`
<img width="1711" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/1da2986d-4dfd-4448-a320-777032faa14a">

Can you please re-check this or share the url where I can see this issue reproducible.

**Comment by cylevaldez** [comment]
@ravkiran The issue can be seen on any article card. The expected result of the "read more" link should be data-analytics-link-name="**read more: <title of the card>**". 

The one that is missing is the title of the card after read more, so this would mean that the data-analytics-link-name of the "read more" link will be different for each card. Please check the legacy site for reference.

**Comment by cylevaldez** [comment]
@ravkiran The team mentioned that the fix was not applied to these local geos:
https://tempnewsroom.accenture.de/
https://tempnewsroom.accenture.fr/ 
https://tempnewsroom.accenture.it/  
https://tempnewsroom.accenture.es/ 
https://tempnewsroom.accenture.co.uk/
https://tempnewsroom.accenture.sg/
https://tempnewsroom.accenture.pt/
https://tempnewsroom.accenturebr.com

As for the link name value, we can make it standard "read more: <title of the card>". It is ok if the "read more" is in English even in other countries. The legacy site has the same implementation.
