### ISSUE TITLE
171668 [High][Newsroom] - Industry Topic pages [BR, ES, SG, JP, PT, DE] - No news cards displayed

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#299]
Priority - 2 High

Description of the issue: No news cards displayed
Steps to Reproduce: 
Open the url(s): 
Adobe Franklin migrated page:
BR - https://main--accenture-newsroom-br--hlxsites.hlx.live/br/industries/retail
ES - https://main--accenture-newsroom-es--hlxsites.hlx.live/es/industries/retail
SG: https://main--accenture-newsroom-sg--hlxsites.hlx.live/asia-pacific/industries/news
JP: https://main--accenture-newsroom-jp--hlxsites.hlx.live/jp/industries/talent-organization-performance
PT: https://main--accenture-newsroom-pt--hlxsites.hlx.live/pt/industries/talent-organization-performance
Legacy newsroom page:
BR: https://newsroom.accenturebr.com/br/industries/retail/
ES: https://newsroom.accenture.es/es/industries/retail/
SG: https://newsroom.accenture.sg/asia-pacific/news/
JP: https://newsroom.accenture.jp/jp/industries/talent-organization-performance
PT: https://newsroom.accenture.pt/pt/industries/talent-organization-performance

Expected Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/b0d431d8-2e39-47ba-89ff-85299e3c2f63)

Actual Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/2e516f00-ca87-42a3-b3aa-c1b84ff1f6ee)

Adobe Franklin migrated page:
DE: https://tempnewsroom.accenture.de/de/industries/banken
Legacy newsroom page:
DE: https://newsroom.accenture.de/de/industries/banken#

Expected Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/15788d69-8765-45c9-ad16-1ad44ea6ac86)

Actual Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/42375b35-ff91-49ed-9ade-c6b2a06a7d6f)

**Comment by amol-anand** [comment]
Please test this again. the links look fine to me
Example from BR:
![Screenshot 2023-10-11 at 1 35 42 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/deeecad7-1a8d-4272-b223-b1f9155e3edb)

**Comment by ravkiran** [comment]
@zozo-j 

The following are empty as there're no matching news for these categories

https://newsroom.accenture.jp/jp/industries/talent-organization-performance
https://newsroom.accenture.pt/pt/industries/talent-organization-performance

https://main--accenture-newsroom-de--hlxsites.hlx.live/de/industries/banken isn't showing the results as https://main--accenture-newsroom-de--hlxsites.hlx.live/query-index.json?offset=0&limit=255&sheet=articles is still showing cached json. I've reached out internally to flush this out, this may take some time.

Except the above every other url is showing the news cards.

created https://github.com/hlxsites/accenture-newsroom/issues/328 for /news/ articles

**Comment by ravkiran** [comment]
cache for https://main--accenture-newsroom-de--hlxsites.hlx.live/query-index.json?offset=0&limit=255&sheet=articles is cleared, now https://main--accenture-newsroom-de--hlxsites.hlx.live/de/industries/banken is working fine. 
cc: @zozo-j

**Comment by ravkiran** [comment]
Please note that https://tempnewsroom.accenture.de/de/industries/banken is still not working as https://tempnewsroom.accenture.de/query-index.json?offset=0&limit=255&sheet=articles is cached in your CDN level.
But this is working fine in https://main--accenture-newsroom-de--hlxsites.hlx.live/de/industries/banken as https://main--accenture-newsroom-de--hlxsites.hlx.live/query-index.json?offset=0&limit=255&sheet=articles is working fine.
