### ISSUE TITLE
250619 - [Newsroom][Site Features and Functionality] - News Posting - Media Content - Wrong authoring of video (Youtube/Vidyard)

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#305]
**Severity - 2 - High**

Issue: Authoring issue on video contents (Youtube/Vidyard)

**Expected:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/98791fc1-a8f8-4848-bd21-d5747d4eb034)
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/31bb532f-d1a5-4e83-93ce-ff63e425df6b)

**Actual:**
https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-song-wins-dan-wieden-titanium-grand-prix-for-tuvalu-the-first-digital-nation
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/2d6b0f36-9947-4618-9b18-b5fc09628d3d)

![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/f51a9f49-bd9e-4d8d-8bb6-9e6cd3e4fe51)

Azdo link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/250619
CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by jjjaspher** [comment]
Hi @ravkiran @amol-anand , is there a purpose of nesting video table inside table component? we're not sure if it's mistaken and we can just modify it.

CC: @raymond-h-dev

**Comment by amol-anand** [comment]
No reason to nest. This must be an issue when we added support for tables in the import script. go ahead and change it in authoring you just need the video block.

**Comment by ravkiran** [comment]
I see there 86 documents in `en` where this is happening, I've fixed the content in the documents, but bulk preview/publish didn't work as these are from the search results in sharepoint. I've preview/published https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-song-wins-dan-wieden-titanium-grand-prix-for-tuvalu-the-first-digital-nation its working fine

**Comment by ravkiran** [comment]
Fixed all the pages, previewed and published
