### ISSUE TITLE
261907 [ASA] [Security Scan] Two headers appear twice with different values

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#309]
During code scan, two headers appear twice with different values.

- strict-transport-security
- cache-control

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/261907

cc: @raymond-h-dev @ravkiran @amol-anand

**Comment by ravkiran** [comment]
@zozo-j 
are you referring to duplicate headers in https://tempnewsroom.accenture.com/ ?
<img width="1277" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/fbfa1098-4672-41fa-97c0-d9fe5f25a808">

Looks like Franklin origin is sending these headers
```
Cache-Control: max-age=7200, must-revalidate
Strict-Transport-Security: max-age=31557600
```
<img width="1077" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/20d72d51-cb90-4125-8453-c2e46cdda60b">


When duplicate headers are there, most of the clients will combine the directives, but its recommended to have only one. 

Can you please check with your CDN team, to override properly or just use the ones coming from upstream (Franklin Origin)
cc: @amol-anand

**Comment by amol-anand** [comment]
Something for the ACC CDN team to look at

**Comment by raymond-h-dev** [comment]
@ravkiran  @amol-anand - i will look into this and gonna update our CDN to get rid the duplicate security headers. thanks for the inputs!

**Comment by veejayricana** [comment]
Security Team done testing this bug, putting this to state close.
