### ISSUE TITLE
published dates is all 0 for es site

### ISSUE THREAD

**Issue by ravkiran** [hlxsites/accenture-newsroom#310]
https://main--accenture-newsroom-es--hlxsites.hlx.page/
<img width="1520" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/677806a7-c2fd-448c-994a-c5f91f148f8d">

**Comment by veejayricana** [comment]
Hi @ravkiran add comment in discussion in this PR : https://github.com/hlxsites/accenture-newsroom/pull/291
I use wrong country selector in translating the date publish. You use SP in country selector function, but I use ES in my date translation function this function will base his country on your country selector that you create so in this pr i correct my countrydatetranaslation function to base on you countty function eaqual to SP.

**Comment by ravkiran** [comment]
added the publisheddate for the legacy site and reimported content, this is fixed now.
