### ISSUE TITLE
222320 - [High] [Newsroom] [E2E Testing] https://tempnewsroom.accenture.com/search?q=service - Different number of Results for "service" search and no tooltip for pagination

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#312]
**Description of the issue:** Upon accessing the search page of Newsroom, try to search a keyword "service then it will be directed to the search result page.  On Legacy, there are 490 results but for migrated page, it has 1625 results.  Also, as per Legacy, there is no tool tip for pagination and not on center position of the page.

**Steps to replicate:**
1. Access the Legacy page and the Migrated page.
2. Compare the look and feel of the search page. 
3. Try to search a keyword on the search bar, using "service"
4. The search result page will show.
5. Check the number of results and look for pagination.

**Legacy:**
https://newsroom.accenture.com/search_results.cfm

**Migrated:**
https://tempnewsroom.accenture.com/search?q=service

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/521814cd-939f-4b17-9fcb-b75cfe1472b9)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/4dee2ea4-ec07-4081-9eac-e6e15315dda8)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/4b3ef9c4-7ce4-4fd5-acac-719b5fd7d1c5)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/b832683c-3e0f-4706-8d28-831c3de93002)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/222320
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana 
1. adding a tooltip is for accessibility best practice, we don't want to remove these things as its not there in legacy. This is also consistent with pagination in the home page
2. We're not using the same backend search like the legacy, the results won't be exactly same. All these results will definitely have the word service, so its showing those many results
3. regarding the pagination in center, this is same consistent experience as in home page.
