### ISSUE TITLE
224304- [High] [Newsroom] [E2E Testing] https://tempnewsroom.accenture.co.uk/search - Different number of Results for "Business" search

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#313]
**Description of the issue:**  Upon accessing the search page of Newsroom, try to search a keyword "business" then it will be directed to the search result page.  On Legacy, there are 76 results for this keyword and has pagination after the news cards lists.  Pagination has tooltip and positions at the center as per migrated.

**Steps to replicate:**
1. Access the Legacy page and the Migrated page.
2. Compare the look and feel of the search page. 
3. Try to search a keyword on the search bar, using "business"
4. The search result page will show.
5. Check the number of results and look for pagination.

Legacy:  https://newsroom.accenture.co.uk/search_results.cfm
Migrated:  https://tempnewsroom.accenture.co.uk/search?q=business

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/764ab896-a6ed-46c0-937a-e2e38c98148e)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/51197cc1-ea34-4d6b-b46c-7197cc01a6fb)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/06ad40d3-076b-49f4-b8f0-3596d1591fb2)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/126b1a87-5dec-407f-8a94-5626d94503b6)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/224304
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana Please understand that legacy and Franklin search are different. Legacy search will search in the whole content where as franklin will search in the title/description/abstract which is typically sufficient. So the results count will be different.
