### ISSUE TITLE
263949 - [High][Newsroom] [E2E Testing] https://main--accenture-newsroom-de--hlxsites.hlx.live/search?q=business - Different number of Results for "business" search

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#314]
**Description of the issue:**  Upon accessing the search page of Newsroom, try to search a keyword "business" then it will be directed to the search result page.  On Legacy, there are 79 result and there is pagination without tooltips for this keyword but on migrated there are 21 results and has tooltips.

**Steps to replicate:**
1. Access the Legacy page and the Migrated page.
2. Compare the look and feel of the search page. 
3. Try to search a keyword on the search bar, using "business"
4. The search result page will show.
5. Check the number of results and look for pagination.

Legacy:
https://newsroom.accenture.de/search_results.cfm

Migrated:
https://main--accenture-newsroom-de--hlxsites.hlx.live/search?q=business

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e2a76b0f-0c90-4e36-85c1-5ea3e616cbcc)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/d1af7d5e-900d-45ac-aaeb-c7df46d05bf3)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/440d3bbc-3590-43bf-9609-9eaed8cbed9b)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e88024cd-6953-408a-a730-85d91c94b0bb)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/263949
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana Please understand that legacy and Franklin search are different. Legacy search will search in the whole content where as franklin will search in the title/description/abstract which is typically sufficient. So the results count will be different.
