### ISSUE TITLE
264543 - [High][Newsroom] [E2E Testing] https://main--accenture-newsroom-es--hlxsites.hlx.live/search?q=innovation- Different number of Results for "innovation" search

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#315]
**Description of the issue:**  Upon accessing the search page of Newsroom, try to search a keyword "innovation" then it will be directed to the search result page.  On Legacy, there are 7 result for this keyword but on migrated there are 2 results.

Steps to replicate:

1. Access the Legacy page and the Migrated page.
2. Compare the look and feel of the search page. 
3. Try to search a keyword on the search bar, using "innovation"
4. The search result page will show.
5. Check the number of results and look for pagination.

Legacy:
https://newsroom.accenture.es/search_results.cfm
Migrated:
https://main--accenture-newsroom-es--hlxsites.hlx.live/search?q=innovation

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/d8d3936a-c7e3-4161-bc4a-15b9c5f9c987)
Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0403830f-f370-40a4-9850-209dc4232352)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/264543
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana Please understand that legacy and Franklin search are different. Legacy search will search in the whole content where as franklin will search in the title/description/abstract which is typically sufficient. 

Moreover search engines typically depends on these SEO tags to enhance the search ranking of the content. If you look at the `innovation` search results in legacy it shows this [article](https://newsroom.accenture.es/es/news/accenture-y-google-cloud-ayudan-a-las-organizaciones-a-escalar-los-avances-en-ia-generativa.htm) in the top, the innovation word is almost at the bottom of the article. In search engines, this article will have very low ranking for the word `innovation`. In Franklin search, the results will come from title/description/abstract which are at the top of the page, so has the higher weight.

HTH!
