### ISSUE TITLE
276165 - [High] [Newsroom] [End to End Testing] - Industry Tag not able to pull news article in the newsfeed

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#316]
**Description of the issue:** Article News with tag industries was not fetched on the Industry Landing page of Healthcare

**Steps to replicate:**
1. Access the Cloudfront page of Healthcare.   https://tempnewsroom.accenture.com/industries/healthcare
2. Access the Article news with industries tag of "Healthcare"  https://tempnewsroom.accenture.com/news/2023/accenture-acquires-leading-digital-healthcare-consultancy-nautilus
3. Verify if the article can be found in the "Healthcare" landing page.

**Expected Result:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/eb741a99-dcd9-4ca8-91ac-f70f54f10904)

**Actual Result:** 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0e730bfb-c812-473d-8db3-698844ead94d)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/276165
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana yesterday we did the full reindexing to resolve these issues, its working now
<img width="1513" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/5aa65c26-8a28-4636-9557-3b85d80e19ac">
