### ISSUE TITLE
Training Site Setup

### ISSUE THREAD

**Issue by raymond-h-dev** [hlxsites/accenture-newsroom#317]
- [ ]  Create github fork
- [ ]  Copy some content from en to new sharepoint folder
- [ ]  Update fstab to point to new environment folder
- [ ]  Add metadata, query-index files
- [ ]  Perform Preview and Publish articles

@amol-anand @ravkiran

**Comment by amol-anand** [comment]
This would be a good time to get someone from ACC to perform these steps as part of KT

**Comment by amol-anand** [comment]
We can get on a call and guide you through the steps. please schedule a call and let me know when you need me to join.

**Comment by raymond-h-dev** [comment]
@amol-anand  i have already scheduled a call tomorrow 10am US Eastern time. please inform me of your availability if you are not free at that time.

**Comment by amol-anand** [comment]
This is completed.
