### ISSUE TITLE
283373 - [Newsroom]Content Migration][HIGH] Missing Industry tag, subject tag and Share platforms section.

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#321]
**Severity - 2 - High**
**Steps to Replicate:**

Step1 : Navigate to page https://tempnewsroom.accenture.com/news/2022/accenture-named-a-leader-in-new-idc-marketscape-for-service-providers-for-energy-transition-services-and-new-utilities-business-models

Live Site : https://newsroom.accenture.com/news/accenture-named-a-leader-in-new-idc-marketscape-for-service-providers-for-energy-transition-services-and-new-utilities-business-models.htm

**Expected Result:** Industry tag, Subject tag and Share platforms are visible.
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/29d32637-8549-4846-97b7-514545a9c7fe)

**Actual Result:** Missing Industry tag, Subject tag and Share platforms.
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/fce30741-9908-43b6-8037-ec6fe4b1a072)

Azdo link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/283373
CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by jjjaspher** [comment]
Hi @amol-anand @ravkiran , it seems the metadata table is not authored properly, is it the same case with video table when running the import.js? 
 
<img width="470" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/142872664/038897ea-e3fc-4d32-ac10-d07590bd5bae">

**Comment by amol-anand** [comment]
is this happening for all articles or just some random ones? seems like metadata table is getting generated multiple times?

**Comment by ravkiran** [comment]
My guess is that there may be very few of these instances. It looks like the contents 1.xxx and 2.xxx is considered as ordered list and continued into metadata table as well. I've tried a few things to wrap block in a p and to set some list-style:none styles to get rid of it, but this isn't getting fixed.
I'd say, we should fix this manually and add in the import script to skip this article import, that way we won't reimport and cause the manual work again.

@amol-anand WDYT?

**Comment by jjjaspher** [comment]
@amol-anand, we'll check with the team if there are other impacted pages

**Comment by amol-anand** [comment]
Yeah, let's fix this manually. I haven't seen many pages with this issue.

**Comment by amol-anand** [comment]
Solution: https://github.com/hlxsites/accenture-newsroom/issues/335#issuecomment-1769519113 Once that is done, you can close this ticket.

**Comment by veejayricana** [comment]
Thank you so much @amol-anand for this, it really helps me to track what are the pages that are been affect.

**Comment by veejayricana** [comment]
Closing this issue, done applying the fix manually.
