### ISSUE TITLE
[Analytics][Newsroom] Consent manager buttons are missing the data analytics attributes

### ISSUE THREAD

**Issue by cylevaldez** [hlxsites/accenture-newsroom#322]
Priority: 3 - Medium

**Steps to Reproduce:**
1. Navigate to https://tempnewsroom.accenture.com/, https://tempnewsroom.accenture.jp/, https://tempnewsroom.accenture.de/
2. Inspect the buttons/links that are found in the consent manager
NOTE: This seems to be working before
![image](https://github.com/hlxsites/accenture-newsroom/assets/144980894/ba258a79-e129-475e-9276-40a8331e724c)

Click "Cookies Details" link to get to this page
![image](https://github.com/hlxsites/accenture-newsroom/assets/144980894/533572ee-5bbf-4b82-81c1-c049a05cec91)

**Expected Result:** 
data-analytics-link-name = link name of button
data-analytics-link-type = cta
data-analytics-module-name = consent manager 
data-analytics-template-zone = consent manager

**Actual Result:**
Null

**Comment by ravkiran** [comment]
@cylevaldez 
In the legacy page, I see the data-analytics-module-name and data-analytics-template-zone attributes on the container and data-analytics-link-name and data-analytics-link-type on the actual element.

<img width="1381" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/e22d1b4e-ebb8-4a16-bac8-590f00e67901">

<img width="1413" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/417f2be0-e0ff-4589-a8de-bde14b9c41c2">

Is it ok to move all the attributes to the actual element? for example all the 4 analytics attributes will be added to `li` element `category-menu-switch-handler ot-active-menu`. 
Please confirm.

**Comment by cylevaldez** [comment]
@ravkiran Yes, it is ok to move all the attributes to the actual element

**Comment by cylevaldez** [comment]
Hey @amol-anand, it seems that the update only took effect on the global site. Can we also update the other geos as well? Thanks

**Comment by raymond-h-dev** [comment]
@cylevaldez  i already been updated the local site repo. please recheck. thanks! cc: @ravkiran @amol-anand
