### ISSUE TITLE
169521 [Geos En pt br uk][High][Newsroom] Common Modules - Hero-hero article for legacy got updated but not for franklin

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#323]
Steps to Reproduce: | Analysis & Proposed Solution: | Location of the Element:

Priority: 3 - Medium

1.Open both the URL 

Legacy
https://newsroom.accenture.com/
https://newsroom.accenture.pt/
https://newsroom.accenturebr.com/
https://newsroom.accenture.co.uk/
Franklin
https://main--accenture-newsroom--hlxsites.hlx.live/
https://main--accenture-newsroom-pt--hlxsites.hlx.live/
https://main--accenture-newsroom-br--hlxsites.hlx.live/
https://main--accenture-newsroom-uk--hlxsites.hlx.live/

2.Observe the hero article for the legacy and franklin, for legacy page it is now updated to latest article but for franklin it is not updated.

Actual:
Legacy article is updated.

Franklin: Franklin page hero article need to be update as per the legacy

Note:
For the other geos mentioned on the bug heading (pt br uk)
There is no hero section for the legacy but for franklin it needs to be update (not sure)

Also, for the other geos i do not see any update on the legacy itself with the latest article ((But this need to be check)

Legacy page
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/7b5250fd-f190-424a-b2f7-f8f4a20e9699)

Franklin page
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/7b2679cb-309d-4a89-92f8-5fd1be68bf12)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/169521

CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by zozo-j** [comment]
- [ ] Authoring
- [ ] en
- [ ] br
- [ ] pt
- [ ] jp
- [ ] de
- [ ] uk
- [ ] es
- [ ] it
- [ ] sg
- [ ] fr
- [ ] Ready for test

**Comment by ravkiran** [comment]
@zozo-j is this authoring issue? now the home pages of legacy and Franklin looks same but the Franklin site should be authored to add the new link https://www.accenture.com/pulseofchange

**Comment by amol-anand** [comment]
This is an authoring issue. need to update the index page for each geo. we are not importing the index page, just the news articles. Please go ahead and update the index page with the right hero article, title, link etc..
