### ISSUE TITLE
242347 - [Newsroom][Content Migration] [HIGH] - News articles are not in Tile View and has No Date Range

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#334]
Steps to Reproduce: 

Step1 : https://tempnewsroom.accenture.com/news
Live Site : https://newsroom.accenture.com/news

Step2: Navigate to Filter News
            No Date Range found

Expected Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/77f378e4-3e76-4232-a44e-3fd06d05c0b7)

Actual Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/f0a9a264-0156-4073-be97-71ae386bb415)

Step3: Navigate to Article Profiles
            Format is not on Tile View

Expected Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/995fb453-bfff-45d1-832c-1716ac6112d2)

Actual Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/de717f85-6733-46d0-a62e-cc9e6bcebdac)

cc: @raymond-h-dev @ravkiran @amol-anand

**Comment by amol-anand** [comment]
If there is already an issue associated with this - please add a comment there rather than opening another issue about the same topic.

**Comment by amol-anand** [comment]
Updated all of the /news pages (all geos) manually to use the newslist block. Previewed and Published. Closing this ticket
