### ISSUE TITLE
290317 - [Newsroom]Content Migration][HIGH] Missing Industry tag, subject tag and Share platforms section.

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#335]
Steps to Replicate:

Step 1: Navigate to page
Migrate: https://tempnewsroom.accenture.com/news/2018/accenture-interactive-acquires-swedish-customer-relationship-management-firm-kaplan

Legacy:  https://newsroom.accenture.com/news/accenture-interactive-acquires-swedish-customer-relationship-management-firm-kaplan.htm

Expected Result: Industry tag, Subject tag and Share platforms are visible.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/17e5b362-3ab7-4e39-97ea-6fa8f9cc3c40)

Actual Result: Missing Industry tag, Subject tag and Share platforms.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/945fcee6-a1aa-4815-aaae-d933c69c4c27)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/290317
cc: @raymond-h-dev @ravkiran @amol-anand

**Comment by veejayricana** [comment]
I already apply a fix in this issue, but I need a Root Cause Analysis why this issue persists on some of the document:

Here is the copy of the document before I apply the fix:

- [accenture-interactive-acquires-swedish-customer-relationship-management-firm-kaplan](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B528EF9D6-DEDB-48A4-B159-DC4E170F709B%7D&file=[accenture-interactive-acquires-swedish-customer-relationship-management-firm-kaplan.docx](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B528EF9D6-DEDB-48A4-B159-DC4E170F709B%7D&file=accenture-interactive-acquires-swedish-customer-relationship-management-firm-kaplan.docx&action=default&mobileredirect=true)&action=default&mobileredirect=true)
- [accenture-reports-strong-first-quarter-fiscal-2018-results](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7BC03470D2-6E02-409D-A554-26168D3ABF2F%7D&file=[accenture-reports-strong-first-quarter-fiscal-2018-results.docx](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7BC03470D2-6E02-409D-A554-26168D3ABF2F%7D&file=accenture-reports-strong-first-quarter-fiscal-2018-results.docx&action=default&mobileredirect=true)&action=default&mobileredirect=true)

Metadata table been distorted.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/fc0f1d12-bea3-4bb3-81b8-3a747cea4ffb)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/363164b3-bcc8-43ff-9146-1cedd37357d2)


And do have a way to check what are the documents that are been affect by this issue?

@raymond-h-dev

**Comment by amol-anand** [comment]
We can grep each document using docxtools and find any specific pattern to tell us which docs might be impacted. 

This is an import script that is automating import of all your content. The original content is not uniform and is structured differently across all your sites. That's why you would see something like this because maybe this and a few other articles have some weird formatting in the original document causing this issue.

**Comment by amol-anand** [comment]
Related issue: https://github.com/hlxsites/accenture-newsroom/issues/321

**Comment by amol-anand** [comment]
Ok so here's what I did
1. Copy the query-index locally
2. went to the helix-default tab and filtered on Template column selecting blanks (basically looking for which articles don't have the template metadata)
3. That gives me the following list

[missing-template.xlsx](https://github.com/hlxsites/accenture-newsroom/files/13034642/missing-template.xlsx)

4. The /news/... articles in this list is missing template which means they are more likely to have the above problem.
5. Please go into these articles and fix the page metadata manually and preview/publish them again and that will fix this problem.

cc: @raymond-h-dev @veejayricana

**Comment by veejayricana** [comment]
Thank you so much @amol-anand for this, it really helps me to track what are the pages that are been affect.

**Comment by veejayricana** [comment]
Closing this bug. 

Note: Fix has been applying and reflected to live. Thanks for the RCA and way of tracking it @amol-anand .
