### ISSUE TITLE
282877 - [Newsroom] [News Posting/Article] Body Copy - Double spacing in article preview page

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#341]
Description: The Article preview page shows double spacing after the first paragraph, even without double spacing in authoring.
-Same double-spacing issue is encountered between Article title and first paragraph.

Preview: https://main--accenture-newsroom--hlxsites.hlx.page/drafts/jay/accenture-names-hilary-o-meara-country-managing-director-for-ireland
Authoring: https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B836743FF-3783-4A95-9DDB-5A15CBFF42D2%7D&file=[accenture-names-hilary-o-meara-country-managing-director-for-ireland.docx](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B836743FF-3783-4A95-9DDB-5A15CBFF42D2%7D&file=accenture-names-hilary-o-meara-country-managing-director-for-ireland.docx&action=default&mobileredirect=true)&action=default&mobileredirect=true

Screenshots:
Authoring:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/8eed5a22-abd8-443e-9e8f-7cad52f87486)

Preview:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/d04d52e3-660a-4385-a580-12596643e169)
Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/282877
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by veejayricana** [comment]
Hi @amol-anand, can we adjust it on your word document importer or sync tool for article, to not create or add another space in the word document that showed above? We received a more than 100 pages that has this issue.

cc: @raymond-h-dev @jjjaspher

**Comment by amol-anand** [comment]
Reopening the issue since I need to still reimport the articles again with this fix in place. Once that is done I will comment and close this issue.

**Comment by veejayricana** [comment]
Hi @amol-anand upon checking on the list of pages that been reported by the QA team, most of the page still have double space.
sample1 : 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/83dece09-0cd0-4ef8-ad2c-8a67bbea263a)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e93542f4-1a07-4be9-b5eb-4b0839e86144)
word docx: [more-than-100000-accenture-employees-received-world-class-technology-education-through-10-year-collaboration-with-the-massachusetts-institute-of-technology](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7BFD034AA4-AA2E-4DBF-AD05-8DE1F71CDB61%7D&file=[more-than-100000-accenture-employees-received-world-class-technology-education-through-10-year--collaboration-with-the-massachusetts-institute-of-technology.docx](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7BFD034AA4-AA2E-4DBF-AD05-8DE1F71CDB61%7D&file=more-than-100000-accenture-employees-received-world-class-technology-education-through-10-year--collaboration-with-the-massachusetts-institute-of-technology.docx&action=default&mobileredirect=true)&action=default&mobileredirect=true)

Sample 2:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/cb9ebd94-87ed-4b54-92b0-3d47f1d6a1b1)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/bdfa2058-5f60-4798-a807-f7f02526eef1)
Word docx:[accenture-announces-intent-to-acquire-leading-epm-solutions-consulting-company-nellarmonia
](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B1CE67854-0E5E-4D46-9F4D-C017AB86C5D0%7D&file=[accenture-announces-intent-to-acquire-leading-epm-solutions-consulting-company-nellarmonia.docx](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B1CE67854-0E5E-4D46-9F4D-C017AB86C5D0%7D&file=accenture-announces-intent-to-acquire-leading-epm-solutions-consulting-company-nellarmonia.docx&action=default&mobileredirect=true)&action=default&mobileredirect=true)
cc: @zozo-j @raymond-h-dev @jjjaspher

**Comment by amol-anand** [comment]
That's how the original content is on your site. We are not adding the additional spaces. What we were adding was a break before and after the --- which has been removed.
 
![Screenshot 2023-10-20 at 12 27 22 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/cb44796b-f063-4597-9c27-d6a295fcdfd7)

**Comment by amol-anand** [comment]
I'm waiting for a decision from ACC w.r.t the fact of removing existing BR's in the original source content. Once that decision is made, I will continue to reimport for other Geo's. Until then, I'll wait for the decision.

**Comment by amol-anand** [comment]
@raymond-h-dev @veejayricana can you please confirm this?

**Comment by amol-anand** [comment]
Closing this issue since we have already fixed the extra spaces that we added around --- but have not touched anything that is coming from the original content.
