### ISSUE TITLE
[Analytics][Newsroom] Missing demandbaseCDC_script

### ISSUE THREAD

**Issue by cylevaldez** [hlxsites/accenture-newsroom#342]
Priority: 3 - Medium

Demandbase variables are fetched from Demandbase extension through an API call.
These variables dmdbase1(eVar14), dmdbase2(eVar66), dmdbase3(eVar85) are populated upon success request of the API.
Based on the legacy page (https://newsroom.accenture.com), an inline script for demandbaseCDC_callback is added which includes a function callback accessing to demandbase API. Upon page source inspection of the migrated page (https://tempnewsroom.accenture.com), the inline script can't be found which is related to demandbase and/or refererring to its API.

**Resolution:**
Include the following script in the head tag. 
<script type="text/javascript" class="optanon-category-2"> 
			var demandbaseCDC_script = document.createElement('script'); 
			demandbaseCDC_script.type = 'text/javascript'; 
			demandbaseCDC_script.async = true; 
			demandbaseCDC_script.src = '//api.demandbase.com/api/v2/ip.json?key=126cd7070cfc0c3ab3e70e653cde6887&callback=Dmdbase_CDC.callback'; 
			document.getElementsByTagName('head')[0].appendChild(demandbaseCDC_script); 
			console.log('functional - demandbaseCDC_callback script added'); 
		</script>
<script type="text/javascript" async="" src="//api.demandbase.com/api/v2/ip.json?key=126cd7070cfc0c3ab3e70e653cde6887&amp;callback=Dmdbase_CDC.callback"></script>

![image](https://github.com/hlxsites/accenture-newsroom/assets/144980894/b4932201-9556-40a1-b4b9-5b8da4e0f442)

cc: @ravkiran @amol-anand

**Comment by amol-anand** [comment]
CDN is adding it's own CSP header which needs to allow for demandbase. Keeping this issue open until that is fixed.

**Comment by amol-anand** [comment]
There is a CSP coming from the CDN side in a header that is clashing with the CSP we have added in Franklin. Your CDN CSP does not have certain paths like demandware to allow those scripts to run. Please fix this by removing the CSP your CDN is adding to the response headers.
