### ISSUE TITLE
313020 - [Newsroom] [UAT Testing] - Critical Pages - Tech Vision 2023 - Missing 3D Image

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#343]
Description: Missing 3d image in migrated page.

Legacy: https://newsroom.accenture.com/news/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds.htm

Migrated: https://tempnewsroom.accenture.com/news/2023/accenture-technology-vision-2023-generative-ai-to-usher-in-a-bold-new-future-for-business-merging-physical-and-digital-worlds

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/40ea927e-1595-4a9c-b4ff-cc3a162fe5a8)
Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/134b2d76-43df-4f2d-a979-19123967c3de)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/313020
cc: @raymond-h-dev @amol-anand @ravkiran

**Comment by amol-anand** [comment]
Issue is fixed by providing an embed block for this type of player.
Re-opening it until a fresh import of content is done and then will close it out.

**Comment by veejayricana** [comment]
Hi @amol-anand 3D image is now visible in .page and .live but not is in CloudFront link :
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0214df66-d1f0-41a4-bf1f-0de722f8d6df)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0f56c7cf-1138-4746-92e2-19e6763a987a)
As I discuss this to @raymond-h-dev he will fix in CloudFront while waiting for that fix I will not close this issue and keep you posted.

**Comment by amol-anand** [comment]
Yeah, just flush the Cloudfront cache for now and that should fix the issue.

**Comment by veejayricana** [comment]
QA team already done testing and tagging this as Close.

cc: @raymond-h-dev @amol-anand @ravkiran
