### ISSUE TITLE
316280 - 401 unauthorized when accessing the training/staging site

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#349]
We are getting 401 unauthorized when accessing the training/staging site. Per Amol we need an API KEY for this site to send because this is a new site.
Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/316280

cc: @amol-anand @ravkiran @raymond-h-dev

**Comment by raymond-h-dev** [comment]
this is good now @veejayricana
