### ISSUE TITLE
313762 - [Newsroom] [UAT Testing] - Critical Pages - Download Press Release button behavior

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#354]
Description:
The download press release button converts the article to pdf and directly downloads the whole article when clicked. Same behavior is encountered on both migrated and legacy page.

Instead of being downloaded automatically, the button should open a new tab that displays the article as PDF and has the option/button to download the said PDF.

Legacy: https://newsroom.accenture.com/news/accenture-reports-fourth-quarter-and-strong-full-year-fiscal-2023-results.htm
Migrated: https://tempnewsroom.accenture.com/news/2023/accenture-reports-fourth-quarter-and-strong-full-year-fiscal-2023-results

 
Expected: PDF should be opened in new tab.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0f6db5d8-8f82-42af-ba6d-a06db17f43bc)

Actual(Migrated and Legacy): PDF is not opened in new tab and downloaded automatically.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/52c28281-5b8e-490f-9253-12e816f7c482)
Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/313762
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Our functionality is the same as on the legacy site. How is this a bug? 
This also depends on your browser defaults. If you want additional new functionality, mark it as such and this cannot be high priority because it doesn't work like that on your current site either.
