### ISSUE TITLE
312238 - [Newsroom] [UAT Testing] - Critical Pages - Fact Sheet - Different table style and format

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#357]
Description: The table in migrated page has different format and style.

Legacy: https://newsroom.accenture.com/fact-sheet/
Migrated: https://tempnewsroom.accenture.com/fact-sheet

Expected: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/074a4c41-06a9-4761-81eb-d43e37df658e)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/5de070de-b72f-4b79-9ae1-38621bd7183d)
Actual: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/12e8d42c-1a40-4f78-b3f5-bb5272b09ea6)
Azdo Link:  https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/312238
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Need to add table block to the codebase. Import script has been updated to import tables in a table block
