### ISSUE TITLE
311529 - [Newsroom] [UAT Testing] - Critical Pages - Earning Infographic - Images are smaller than original ones

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#358]
Description: Images are smaller than original ones

Legacy: https://newsroom.accenture.com/earnings-infographics/
Migrated: https://tempnewsroom.accenture.com/earnings-infographics

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/dc4f1d50-f472-4701-bf86-73c0ecea9ed2)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/1383e354-55ea-4534-9093-5a42a5197682)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/b0d13547-de21-481c-a83b-e3ec80c031cd)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e3b55c0a-ef25-4edf-a581-1878f436d78d)

Azdo  link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/311529
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
The image is respecting the width of the article body so it does not look out of place.

**Comment by amol-anand** [comment]
This is the issue:
Original image width is 793. so it is only going so much. Your current site is stretching the image to be full width 100% which also looks like it is a little lower quality.

Is it possible to give us the original image that has a higher width so it looks nicer? Then we can update it.

@jjjaspher @raymond-h-dev

**Comment by jjjaspher** [comment]
@amol-anand , as per discussion with Eula and Iliyaz, you can implement the 100% image regardless of the quality. We'll just cater the higher quality post live.
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/d550c617-f9c9-411f-b9db-595ef6ef3670)

**Comment by amol-anand** [comment]
Should we do this for ALL images in the content?

**Comment by jjjaspher** [comment]
@amol-anand, I've set the image width to 100% as default, it seems this has no impact to other image. Please review once. Thank you
https://github.com/hlxsites/accenture-newsroom/pull/383
