### ISSUE TITLE
312765 - [Newsroom] [UAT Testing] - Critical Pages - Metaverse - Font size difference on image caption

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#359]
Description: Image caption displays larger in migrated page.

Legacy: https://newsroom.accenture.com/news/growing-consumer-and-business-interest-in-the-metaverse-expected-to-fuel-trillion-dollar-opportunity-for-commerce-accenture-finds.htm
Migrated: https://tempnewsroom.accenture.com/news/2023/growing-consumer-and-business-interest-in-the-metaverse-expected-to-fuel-trillion-dollar-opportunity-for-commerce-accenture-finds

Expected: Image
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/29fd98b0-94d9-424d-badb-d93a54812265)
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/7ca5d246-e396-45a7-9666-90ab7b00e553)
Actual
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/3ac6d3cb-b931-4235-bb8c-d7b19c7b8c7b)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/312765
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by Jaykaaa** [comment]
Please provide your commitment date on fixing this bug. We need to fix this bug this week.
