### ISSUE TITLE
312754 - [Newsroom] [UAT Testing] - Critical Pages- 2D to 3D- Incorrect image caption font format

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#361]
Description: The caption for the missing 3D image should be a smaller font.

Legacy: https://newsroom.accenture.com/news/accenture-invests-in-looking-glass-to-accelerate-shift-from-2d-to-3d.htm
Migrated: https://tempnewsroom.accenture.com/news/2023/accenture-invests-in-looking-glass-to-accelerate-shift-from-2d-to-3d

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/4b68f4eb-34b0-4085-ac75-54ebce200f5b)

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e215438f-5285-4d37-8c78-ec68895e7f49)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/312754
cc: @raymond-h-dev @amol-anand @ravkiran

**Comment by amol-anand** [comment]
@veejayricana please open a PR with the fix for issues like this. I would not waste time logging the issue itself. just provide the CSS fix for it instead and open a PR.
cc: @raymond-h-dev

**Comment by jjjaspher** [comment]
Hi @amol-anand, I think the problem here is we don't have unique identifier to target which needs to have smaller fontsize.
Just like this issue 359, italic with smaller fontsize can be anywhere to the page. 
As we observed this italic small fontsize usually a caption to the image or 3D image, so is it possible to have image component that has caption field?
https://github.com/hlxsites/accenture-newsroom/issues/359
CC: @raymond-h-dev

**Comment by amol-anand** [comment]
Instead of that what I would suggest is to find the italics/emphasized text that is right AFTER an image, and style those accordingly.

cc: @ravkiran

**Comment by ravkiran** [comment]
@amol-anand in #359 styling italics/em after an image makes sense but in this case, its not an image, but an embed block. So, we can't find this italics/em like in #359.
The DOM looks like this
<img width="1273" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/c8f9996c-75d8-4fad-ac80-26419b8d85e0">

We've styled h6 in abstract as center aligned with font size 16px. But this needs 12px, so 
I see the following options

1. we can add this caption directly in the embed block itself. I see this block used ~6 times, so we should be able to manually update these
2. we can style h6 with underline as center and font 12px. 

WDYT?

**Comment by amol-anand** [comment]
Can't we look for italics/em after an embed block and style it this way as well? similar to #359 ? same logic, just looking for it/emphasis right after an image/embed block

**Comment by ravkiran** [comment]
I've used `h6 em in article will be center aligned with font size 12px`
