### ISSUE TITLE
310824 - [Newsroom] [UAT Testing] - Critical Pages - Homepage - Missing link in secondary/multi navigation

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#362]
Description: "Pulse of change" link is missing in secondary/multi navigation.

Legacy: https://newsroom.accenture.com/
Migrated: https://tempnewsroom.accenture.com/

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/1b804ec6-4a6c-48ff-81c6-f3f34ff5349b)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/85836216-a2dc-47f7-be3e-8ef62a1deb70)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/310824
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
Please add this to the content directly. Please don't open issues for things that can be easily fixed yourself by updating the Word document. It's a waste of your time 😄 

@raymond-h-dev

**Comment by veejayricana** [comment]
@amol-anand Yes, I try to add one sub-navigation on the word document, but I think, are currently UI design is only accommodating 4 or less link and also, they want to retain the arrow icon.

Test Page:
https://main--accenture-newsroom--hlxsites.hlx.page/drafts/jay/https://main--accenture-newsroom--hlxsites.hlx.page/drafts/jay/
docx: https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B4A8C6009-9545-4652-987E-2E23EA4776DA%7D&file=index.docx&action=default&mobileredirect=truehttps://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B4A8C6009-9545-4652-987E-2E23EA4776DA%7D&file=index.docx&action=default&mobileredirect=true

cc: @raymond-h-dev @jjjaspher

**Comment by amol-anand** [comment]
Please send us a PR with the CSS fix 😄 

@raymond-h-dev

**Comment by veejayricana** [comment]
This be on hold and waiting for the business approval for the behavior of the multi-sub nav.
