### ISSUE TITLE
311603 - [Newsroom] [UAT Testing] - Critical Pages - Ops Resilience - Color of Accenture logo is different in both mobile and desktop view

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#364]
Description: Color of Accenture logo is different in both mobile and desktop view

Legacy: https://newsroom.accenture.com/news/among-c-suite-leaders-ai-is-top-digital-priority-in-the-path-to-operational-resilience-finds-accenture-study.htm
Migrated: https://tempnewsroom.accenture.com/news/2023/among-c-suite-leaders-ai-is-top-digital-priority-in-the-path-to-operational-resilience-finds-accenture-study

Expected:
Desktop view:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/a0710165-c2e3-4b76-82a9-bc16ab65422f)

Mobile view:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/7e97391a-8982-4a49-b318-d94ee1e81de1)

Actual:
Desktop view:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/3862b287-7ad5-4ab8-ad63-0978389a9e0b)

Mobile view:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/06511a68-e60e-45c9-b2f9-ce474ea41487)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/311603
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
The logo should be the same. looks like this is an issue on your current site where mobile and desktop have two different colored logos. I assume that's a mistake and ours is consistent with what is on your desktop.

cc: @raymond-h-dev
