### ISSUE TITLE
332119 - [Newsroom] [High] PDFs open in the same tab

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#377]
Description: PDFs both open in the same tab

**Legacy:** https://newsroom.accenture.com/news/accenture-reports-fourth-quarter-and-strong-full-year-fiscal-2023-results.htm
**Migrated:** https://tempnewsroom.accenture.com/news/2023/accenture-reports-fourth-quarter-and-strong-full-year-fiscal-2023-results

**Steps to reproduce:**
1. Navigate to legacy and migrated page.
2. Click on "[Q4 FY23](https://newsroom.accenture.com/content/1101/files/4QFY23_Infographic.pdf)" and "[Full FY23](https://newsroom.accenture.com/content/1101/files/Full_FY23_Infographic.pdf)"
Expected: PDF should be open in new tab without error

Actual: Both PDF should be open in same tab without error

Azdo Link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/332119

**Comment by Jaykaaa** [comment]
@amol-anand @ravkiran Please provide your commitment date on fixing this bug. We need to fix this bug this week. Thanks
