### ISSUE TITLE
[High][Newsroom][Content Migration] - CTA Button inside the content is missing

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#380]
Description of the issue: CTA Button inside the content is missing
Steps to Reproduce: 
Open the url(s): 
Adobe (CF):
1.https://tempnewsroom.accenture.com/news/2021/accenture-reports-very-strong-fourth-quarter-and-full-year-fiscal-2021-results
2.https://tempnewsroom.accenture.com/news/2017/accenture-reports-strong-first-quarter-fiscal-2018-results
Legacy page:
1.https://newsroom.accenture.com/news/accenture-reports-very-strong-fourth-quarter-and-full-year-fiscal-2021-results.htm
2.https://newsroom.accenture.com/news/accenture-reports-strong-first-quarter-fiscal-2018-results.htm
Expected Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/1814899d-fe0c-4b17-9e5c-d32e1f2058fd)
Actual Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/ffb0919b-5778-4ebe-8a4f-e03c35bb9b4b)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/301846
cc: @raymond-h-dev @ravkiran @amol-anand

**Comment by amol-anand** [comment]
Yes, this was removed because those links in the original content don't work (they just open the same page) and we now have the Download Press Release button on the side nav that does the same thing.

**Comment by veejayricana** [comment]
Hi @amol this is the response from business. 
Sample link: https://newsroom.accenture.com/news/accenture-reports-very-strong-fourth-quarter-and-full-year-fiscal-2021-results.htm
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/40beb098-d51f-4023-8920-54220bdfc2af)

**Comment by amol-anand** [comment]
@veejayricana is this the only example or are there other pages with this issue?

**Comment by amol-anand** [comment]
I'm looking into this. found a solution. just checking to see if there are certain pages / urls that have this button that you can tell from your current system or do i need to reimport EVERYTHING all over again.

**Comment by amol-anand** [comment]
re-imported the pages that have the button for all the GEO sites is complete. @ravkiran is reimporting the EN ones. This is fixed now. @ravkiran please close this issue once you are finished.

**Comment by ravkiran** [comment]
en reimport is done and also styled the download button in https://github.com/hlxsites/accenture-newsroom/pull/401

**Comment by veejayricana** [comment]
Hi @ravkiran and @amol-anand, can you check why some email addresses displays as button after we add the click to download.

Migrated: 
https://tempnewsroom.accenture.com/fact-sheet
https://tempnewsroom.accenture.com/news/2022/accenture-to-host-virtual-investor-and-analyst-conference-on-thursday-april-7
Legacy:
https://newsroom.accenture.com/fact-sheet
https://tempnewsroom.accenture.com/fact-sheet
Expected:
1.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/70cfea7b-5ff1-43e3-8b52-281e4311d93b)
2. 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/ccfb0d7c-4620-4501-91db-6eb8747bc0a7)
Actual:
1.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/8186b0a3-9b2f-4e7f-887c-23035d37bfc3)
2. 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/16098bf8-28b1-409d-85cc-284cd52300f0)

**Comment by ravkiran** [comment]
This issue is fixed in #402 
Please check https://tempnewsroom.accenture.com/fact-sheet in incognito
