### ISSUE TITLE
266346 - [Newsroom][Content Migration]- Missing Slide container

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#384]
Steps to Reproduce: 
Open Migrated Newsroom page: https://tempnewsroom.accenture.com/news/more-than-half-of-consumers-would-pay-more-for-sustainable-products-designed-to-be-reused-or-recycled-accenture-survey-finds.htm
Legacy Page:https://newsroom.accenture.com/news/more-than-half-of-consumers-would-pay-more-for-sustainable-products-designed-to-be-reused-or-recycled-accenture-survey-finds.htm
Scroll down to "Accenture Chemicals Global Consumer Sustainability Survey 2019" 

Expected Result: Slide container will display above the "Accenture Chemicals Global Consumer Sustainability Survey 2019" 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/d615aa01-4f21-4f48-9a6c-95317b3c1a28)

Actual Result: Slide Container is not displaying
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/b3181c0c-2aa0-4869-84ba-a916e29a3fa8)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/266346
cc: @ravkiran @raymond-h-dev @amol-anand

**Comment by amol-anand** [comment]
You can use the embed block for this. I just updated the content

Also need to add the url domain to CSP so the browser will allow it to be iframed.
![Screenshot 2023-10-27 at 1 44 21 PM](https://github.com/hlxsites/accenture-newsroom/assets/7074782/c9a56ad2-74a5-48d1-8217-36a285b5a5e4)

Separate issue where CDN is adding it's own CSP at the header. But this issue can be closed now.
