### ISSUE TITLE
231676 - [Newsroom][Content Migration]- No Year Available to Filter

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#386]
Description: No Year available to filter
Steps to Reproduce: 
Open the Migrated Newsroom page: [https://tempnewsroom.accenture.com/industries](https://tempnewsroom.accenture.com/industries?year=)
Legacy Page:https://newsroom.accenture.com/industries/
Filter a year in the dropdown
Expected Result: Once the dropdown is clicked, available years will display
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e8986538-b4ae-45c5-afc2-eb68f0f5b13f)

Actual Result: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/c82403e4-dda1-4942-88dd-f988c0758705)

Azdo Image: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/231676
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana https://newsroom.accenture.com/subjects/ and https://newsroom.accenture.com/industries/ pages will show all the links for the categories. In the current import these are not handled, we can simply create these pages with the respective links. 

But we'll not be adding any articles or filters to these pages, as the filters in the current site are not working and also the articles shown in https://newsroom.accenture.com/industries/ may not have any direct relation to industries itself.

Please check the updated https://tempnewsroom.accenture.com/subjects/ and https://tempnewsroom.accenture.com/industries
