### ISSUE TITLE
231902 - [Newsroom][Content Migration]- Missing Links 

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#387]
Description: No Links displaying
Steps to Reproduce: 
Open the Migrated Newsroom page: [https://tempnewsroom.accenture.com/industries](https://tempnewsroom.accenture.com/industries?year=)
Legacy Page:https://newsroom.accenture.com/industries/
Expected Result: Upon accessing the page Links will display under industries
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/37b07bf3-1677-4e2e-845a-ff90ffcaebae)

Actual Result: Upon accessing the page No Links are displaying under industries
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/b1c0f47f-eba5-43ec-9f2e-fa486eef092c)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/231902
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
this is fixed as part of https://github.com/hlxsites/accenture-newsroom/issues/386
Please check https://tempnewsroom.accenture.com/industries 
But we'll not be adding any articles or filters to these pages, as the filters in the current site are not working and also the articles shown in https://newsroom.accenture.com/industries/ may not have any direct relation to industries itself.
