### ISSUE TITLE
268128 - [Newsroom][Content Migration] URL is not in migrated format

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#388]
DECRIPTION: URL format in migrated page is not in "tempnewsroom" format and is using live URL.

MIGRATED PAGE:
https://tempnewsroom.accenture.com/news/2022/companies-with-highly-interoperable-technology-achieve-six-times-higher-revenue-growth-according-to-new-accenture-research
https://tempnewsroom.accenture.jp/jp/news/2023/release-20230713-2
https://tempnewsroom.accenture.jp/jp/news/2023/release-20230320
https://tempnewsroom.accenture.jp/jp/news/2023/release-20230531
https://tempnewsroom.accenture.jp/jp/news/2020/release-20201015
https://tempnewsroom.accenture.com/news/2022/accenture-report-finds-people-want-easy-to-use-government-customer-services
https://tempnewsroom.accenture.com/news/2023/accenture-life-insurance-and-annuity-platform-achieves-luminary-status-and-wins-xcelent-award
https://tempnewsroom.accenture.com/news/2022/accenture-invests-in-immersive-learning-startup-talespin
https://tempnewsroom.accenture.com/news/2018/accenture-expands-industry-x-0-capabilities-with-two-acquisitions-in-north-america
https://tempnewsroom.accenture.com/news/2021/accenture-expands-cloud-first-offerings-and-engineering-capabilities-in-the-uk-with-acquisition-of-infinity-works
https://tempnewsroom.accenture.com/news/2022/six-in-seven-consumers-desire-simplicity-in-entertainment-experiences-accenture-report-finds
https://tempnewsroom.accenture.com/news/2022/aker-bp-and-accenture-team-up-on-data-factory-in-the-cloud-to-improve-oil-and-gas-operations
https://tempnewsroom.accenture.com/news/2022/accenture-report-details-how-new-technologies-are-enabling-industrial-companies-to-bring-products-to-market-faster
https://tempnewsroom.accenture.com/news/2021/accenture-named-a-leader-in-salesforce-consulting-partners-report-by-independent-research-firm
https://tempnewsroom.accenture.com/news/2020/accenture-completes-acquisition-of-myrtle-consulting-group
https://tempnewsroom.accenture.com/news/2016/accenture-announces-winners-of-innovation-jockeys-season-five
https://tempnewsroom.accenture.com/news/2021/stellantis-tim-and-accenture-collaborate-on-5g-industrial-application-in-brazil
https://newsroom.accenture.com/news/c-suite-leaders-taking-entirely-new-approach-to-costs-according-to-accenture.htm
https://tempnewsroom.accenture.com/news/2021/accenture-and-organon-team-up-to-drive-digital-transformation-for-better-patient-and-employee-experiences
https://tempnewsroom.accenture.com/news/2018/accenture-acquires-daz-systems-inc-to-strengthen-its-oracle-cloud-erp-services-expand-capabilities-to-help-clients-become-intelligent-enterprises
https://tempnewsroom.accenture.com/news/2020/accenture-acquires-byte-prophecy-to-enhance-ai-and-digital-analytics-capabilities-in-emerging-markets
https://tempnewsroom.accenture.com/news/2021/accenture-federal-services-wins-453-million-veterans-affairs-contract-to-support-and-modernize-gi-bill-benefits-processing
https://tempnewsroom.accenture.com/news/2016/consumers-welcome-personalized-offerings-but-businesses-are-struggling-to-deliver-finds-accenture-interactive-personalization-research
https://tempnewsroom.accenture.com/news/2020/accenture-federal-services-wins-federal-retirement-thrift-investment-board-contract-to-improve-retirement-outcomes-for-civil-service-and-military-401k
https://tempnewsroom.accenture.com/news/2020/accenture-acquires-boutique-australian-consultancy-alphabeta-advisors-bolstering-analytics-led-strategy-services
https://tempnewsroom.accenture.com/news/2022/accenture-advances-ai-research-as-inaugural-member-of-corporate-affiliate-program-at-stanford-institute-for-human-centered-artificial-intelligence
https://tempnewsroom.accenture.com/news/2021/accenture-acquires-zestgroup-to-help-clients-procure-a-more-sustainable-future
https://tempnewsroom.accenture.com/news/2021/leading-companies-that-scaled-technology-innovation-during-covid-19-are-growing-revenue-five-times-faster-than-lagging-adopters
https://tempnewsroom.accenture.com/news/2023/accenture-named-top-leader-in-open-finance-it-services-by-everest-group
https://tempnewsroom.accenture.com/news/2022/slow-adoption-of-next-generation-payment-solutions-could-put-up-to-89-billion-in-bank-revenues-at-risk-by-2025-according-to-research-from-accenture
https://tempnewsroom.accenture.com/news/2022/qorus-and-accenture-announce-winners-of-2022-banking-innovation-awards
https://tempnewsroom.accenture.com/news/2022/accenture-strengthens-sustainability-capabilities-with-acquisition-of-akzente
https://tempnewsroom.accenture.com/news/2023/accenture-positioned-as-a-leader-in-european-professional-services-for-data-driven-government-in-idc-marketscape-report
https://tempnewsroom.accenture.com/news/2022/accenture-completes-acquisition-of-greenfish
https://tempnewsroom.accenture.com/news/2021/accenture-acquires-wolox-boosting-cloud-first-and-digital-transformation-capabilities-in-argentina-and-south-america
https://tempnewsroom.accenture.com/news/2023/through-new-strategic-partnership-accenture-and-conga-collaborate-to-help-companies-transform-revenue-lifecycle-management
https://tempnewsroom.accenture.com/news/2023/accenture-to-acquire-objectivity-to-expand-platform-engineering-capabilities-in-europe
https://tempnewsroom.accenture.com/news/2020/accenture-launches-project-spotlight-a-new-approach-to-venture-capital
https://tempnewsroom.accenture.com/news/2022/accenture-and-aws-collaborate-to-upskill-youth-in-india-for-cloud-careers
https://tempnewsroom.accenture.com/news/2020/accenture-announces-changes-to-its-growth-model-and-global-management-committee
https://tempnewsroom.accenture.com/news/2023/accenture-to-announce-third-quarter-fiscal-2023-results
https://tempnewsroom.accenture.com/news/2023/accenture-and-palo-alto-networks-to-provide-integrated-prisma-sase-solutions-to-help-organizations-improve-cyber-resilience
https://tempnewsroom.accenture.com/news/2023/accenture-and-adobe-unlock-content-supply-chain-value-to-help-enterprise-brands-cut-costs-increase-efficiencies-and-drive-growth
https://tempnewsroom.accenture.com/news/2023/accenture-to-accelerate-blue-yonders-development-and-delivery-of-new-solutions-companies-expand-relationship-to-increase-adoption-of-modern-connected-supply-chains
https://tempnewsroom.accenture.com/news/2016/accenture-launches-intelligent-automation-platform-to-deliver-smarter-more-efficient-application-services-that-improve-business-outcomes
https://tempnewsroom.accenture.com/news/2023/unilever-goes-cloud-only-accenture-and-microsoft-complete-one-of-the-largest-cloud-migrations-in-consumer-goods-industry
https://tempnewsroom.accenture.com/news/2023/accenture-and-cervest-collaborate-to-bring-innovative-solutions-to-clients-seeking-resilience-amid-increased-climate-risk
https://tempnewsroom.accenture.com/news/2020/accenture-cloud-first-launches-with-3-billion-investment-to-accelerate-clients-move-to-cloud-and-digital-transformation
https://tempnewsroom.accenture.com/news/2022/accenture-recognized-as-a-top-ten-great-place-to-work-in-six-countries
https://tempnewsroom.accenture.com/news/2022/accenture-appoints-ambe-tierro-as-country-managing-director-for-the-philippines
https://tempnewsroom.accenture.jp/jp/news/2022/release-20221115
https://tempnewsroom.accenture.de/de/subjects/diversity
https://tempnewsroom.accenture.de/de/industries/konsumgter-handel
https://tempnewsroom.accenture.com/news/2001/accenture-opens-two-new-offshore-development-facilities
https://tempnewsroom.accenture.com/news/2021/accenture-ranked-1-in-execution-and-innovation-for-workday-human-capital-management-services-market-in-hfs-research-report
https://tempnewsroom.accenture.com/news/2019/accenture-and-chevron-win-innovation-award-for-system-that-uses-digital-technology-to-improve-worker-safety-in-crane-operations
https://tempnewsroom.accenture.com/news/2020/accenture-and-google-cloud-collaborate-to-help-life-sciences-companies-advance-the-discovery-development-and-delivery-of-innovative-therapies
https://tempnewsroom.accenture.com/news/2017/accenture-and-ponemon-institute-report-cyber-crime-drains-11-7-million-per-business-annually-up-62-percent-in-five-years
https://tempnewsroom.accenture.com/news/2021/accenture-and-salesforce-expand-partnership-to-help-companies-embed-sustainability-into-the-core-of-their-business
https://tempnewsroom.accenture.com/news/2021/accenture-announces-intent-to-acquire-strategy-and-business-management-consultancy-exton-consulting
https://tempnewsroom.accenture.com/news/2021/accenture-business-futures-2021-report-identifies-the-signals-to-guide-companies-navigating-change-in-the-era-of-compressed-transformation
https://tempnewsroom.accenture.com/news/2002/accenture-campaign-breaks-new-ground-for-professional-services-firms-brcenteri-am-your-idea-use-me-center
https://tempnewsroom.accenture.com/news/2015/accenture-completes-acquisition-of-cloud-sherpas-strengthening-enterprise-cloud-capabilities

LEGACY PAGE:
https://newsroom.accenture.com/news/companies-with-highly-interoperable-technology-achieve-six-times-higher-revenue-growth-according-to-new-accenture-research.htm
https://newsroom.accenture.jp/jp/news/release-20230713-2.htm
https://newsroom.accenture.jp/jp/news/release-20230320.htm
https://newsroom.accenture.jp/jp/news/release-20230531.htm
https://newsroom.accenture.jp/jp/news/release-20201015.htm
https://newsroom.accenture.com/news/accenture-report-finds-people-want-easy-to-use-government-customer-services.htm
https://newsroom.accenture.com/news/accenture-life-insurance-and-annuity-platform-achieves-luminary-status-and-wins-xcelent-award.htm
https://newsroom.accenture.com/news/accenture-invests-in-immersive-learning-startup-talespin.htm
https://newsroom.accenture.com/news/accenture-expands-industry-x-0-capabilities-with-two-acquisitions-in-north-america.htm
https://newsroom.accenture.com/news/accenture-expands-cloud-first-offerings-and-engineering-capabilities-in-the-uk-with-acquisition-of-infinity-works.htm
https://newsroom.accenture.com/news/six-in-seven-consumers-desire-simplicity-in-entertainment-experiences-accenture-report-finds.htm
https://newsroom.accenture.com/news/aker-bp-and-accenture-team-up-on-data-factory-in-the-cloud-to-improve-oil-and-gas-operations.htm
https://newsroom.accenture.com/news/accenture-report-details-how-new-technologies-are-enabling-industrial-companies-to-bring-products-to-market-faster.htm
https://newsroom.accenture.com/news/accenture-named-a-leader-in-salesforce-consulting-partners-report-by-independent-research-firm.htm
https://newsroom.accenture.com/news/accenture-completes-acquisition-of-myrtle-consulting-group.htm
https://newsroom.accenture.com/news/accenture-announces-winners-of-innovation-jockeys-season-five.htm
https://newsroom.accenture.com/news/stellantis-tim-and-accenture-collaborate-on-5g-industrial-application-in-brazil.htm
https://newsroom.accenture.com/news/c-suite-leaders-taking-entirely-new-approach-to-costs-according-to-accenture.htm
https://newsroom.accenture.com/news/accenture-and-organon-team-up-to-drive-digital-transformation-for-better-patient-and-employee-experiences.htm
https://newsroom.accenture.com/news/accenture-acquires-daz-systems-inc-to-strengthen-its-oracle-cloud-erp-services-expand-capabilities-to-help-clients-become-intelligent-enterprises.htm
https://newsroom.accenture.com/news/accenture-acquires-byte-prophecy-to-enhance-ai-and-digital-analytics-capabilities-in-emerging-markets.htm
https://newsroom.accenture.com/news/accenture-federal-services-wins-453-million-veterans-affairs-contract-to-support-and-modernize-gi-bill-benefits-processing.htm
https://newsroom.accenture.com/news/consumers-welcome-personalized-offerings-but-businesses-are-struggling-to-deliver-finds-accenture-interactive-personalization-research.htm
https://newsroom.accenture.com/news/accenture-federal-services-wins-federal-retirement-thrift-investment-board-contract-to-improve-retirement-outcomes-for-civil-service-and-military-401k.htm
https://newsroom.accenture.com/news/accenture-acquires-boutique-australian-consultancy-alphabeta-advisors-bolstering-analytics-led-strategy-services.htm
https://newsroom.accenture.com/news/accenture-advances-ai-research-as-inaugural-member-of-corporate-affiliate-program-at-stanford-institute-for-human-centered-artificial-intelligence.htm
https://newsroom.accenture.com/news/accenture-acquires-zestgroup-to-help-clients-procure-a-more-sustainable-future.htm
https://newsroom.accenture.com/news/leading-companies-that-scaled-technology-innovation-during-covid-19-are-growing-revenue-five-times-faster-than-lagging-adopters.htm
https://newsroom.accenture.com/news/accenture-named-top-leader-in-open-finance-it-services-by-everest-group.htm
https://newsroom.accenture.com/news/slow-adoption-of-next-generation-payment-solutions-could-put-up-to-89-billion-in-bank-revenues-at-risk-by-2025-according-to-research-from-accenture.htm
https://newsroom.accenture.com/news/qorus-and-accenture-announce-winners-of-2022-banking-innovation-awards.htm
https://newsroom.accenture.com/news/accenture-strengthens-sustainability-capabilities-with-acquisition-of-akzente.htm
https://newsroom.accenture.com/news/accenture-positioned-as-a-leader-in-european-professional-services-for-data-driven-government-in-idc-marketscape-report.htm
https://newsroom.accenture.com/news/accenture-completes-acquisition-of-greenfish.htm
https://newsroom.accenture.com/news/accenture-acquires-wolox-boosting-cloud-first-and-digital-transformation-capabilities-in-argentina-and-south-america.htm
https://newsroom.accenture.com/news/through-new-strategic-partnership-accenture-and-conga-collaborate-to-help-companies-transform-revenue-lifecycle-management.htm
https://newsroom.accenture.com/news/accenture-to-acquire-objectivity-to-expand-platform-engineering-capabilities-in-europe.htm
https://newsroom.accenture.com/news/accenture-launches-project-spotlight-a-new-approach-to-venture-capital.htm
https://newsroom.accenture.com/news/accenture-and-aws-collaborate-to-upskill-youth-in-india-for-cloud-careers.htm
https://newsroom.accenture.com/news/accenture-announces-changes-to-its-growth-model-and-global-management-committee.htm
https://newsroom.accenture.com/news/accenture-to-announce-third-quarter-fiscal-2023-results.htm
https://newsroom.accenture.com/news/accenture-and-palo-alto-networks-to-provide-integrated-prisma-sase-solutions-to-help-organizations-improve-cyber-resilience.htm
https://newsroom.accenture.com/news/accenture-and-adobe-unlock-content-supply-chain-value-to-help-enterprise-brands-cut-costs-increase-efficiencies-and-drive-growth.htm
https://newsroom.accenture.com/news/accenture-to-accelerate-blue-yonders-development-and-delivery-of-new-solutions-companies-expand-relationship-to-increase-adoption-of-modern-connected-supply-chains.htm
https://newsroom.accenture.com/news/accenture-launches-intelligent-automation-platform-to-deliver-smarter-more-efficient-application-services-that-improve-business-outcomes.htm
https://newsroom.accenture.com/news/unilever-goes-cloud-only-accenture-and-microsoft-complete-one-of-the-largest-cloud-migrations-in-consumer-goods-industry.htm
https://newsroom.accenture.com/news/accenture-and-cervest-collaborate-to-bring-innovative-solutions-to-clients-seeking-resilience-amid-increased-climate-risk.htm
https://newsroom.accenture.com/news/accenture-cloud-first-launches-with-3-billion-investment-to-accelerate-clients-move-to-cloud-and-digital-transformation.htm
https://newsroom.accenture.com/news/accenture-recognized-as-a-top-ten-great-place-to-work-in-six-countries.htm
https://newsroom.accenture.com/news/accenture-appoints-ambe-tierro-as-country-managing-director-for-the-philippines.htm
https://newsroom.accenture.jp/jp/news/release-20221115.htm
https://newsroom.accenture.de/de/subjects/diversity/
https://newsroom.accenture.de/de/industries/konsumgter-handel/
https://newsroom.accenture.com/news/accenture-opens-two-new-offshore-development-facilities.htm
https://newsroom.accenture.com/news/accenture-ranked-1-in-execution-and-innovation-for-workday-human-capital-management-services-market-in-hfs-research-report.htm
https://newsroom.accenture.com/news/accenture-and-chevron-win-innovation-award-for-system-that-uses-digital-technology-to-improve-worker-safety-in-crane-operations.htm
https://newsroom.accenture.com/news/accenture-and-google-cloud-collaborate-to-help-life-sciences-companies-advance-the-discovery-development-and-delivery-of-innovative-therapies.htm
https://newsroom.accenture.com/news/accenture-and-ponemon-institute-report-cyber-crime-drains-11-7-million-per-business-annually-up-62-percent-in-five-years.htm
https://newsroom.accenture.com/news/accenture-and-salesforce-expand-partnership-to-help-companies-embed-sustainability-into-the-core-of-their-business.htm
https://newsroom.accenture.com/news/accenture-announces-intent-to-acquire-strategy-and-business-management-consultancy-exton-consulting.htm
https://newsroom.accenture.com/news/accenture-business-futures-2021-report-identifies-the-signals-to-guide-companies-navigating-change-in-the-era-of-compressed-transformation.htm
https://newsroom.accenture.com/news/accenture-campaign-breaks-new-ground-for-professional-services-firms-brcenteri-am-your-idea--use-me-center.htm
https://newsroom.accenture.com/news/accenture-completes-acquisition-of-cloud-sherpas-strengthening-enterprise-cloud-capabilities.htm

STEPS TO REPLICATE:
Open page in a browser.
Scroll from top to bottom to identify inline links and CTAs
Hover over and see link format.

EXPECTED:
URL should have tempnewsroom in it. See sample below.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/a22a578d-da03-475d-837b-c50717c74198)

ACTUAL RESULT:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/76844c29-c36b-489d-91f3-d048f0c1f252)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/268128
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
These urls will work once we go live. the other option is to change the footer content to use the .page or .live franklin URLs instead and that will respect whichever domain is in front of it. Content change.

**Comment by amol-anand** [comment]
There is only one footer per site. that can be updated to use the .live URL if you choose to do so. Otherwise if left alone, it will work when we make the switch to go live.

**Comment by amol-anand** [comment]
I realized we don't have an archive page. Adding that (copy of the search page basically) and adding redirects from /archive.cfm to /archive in the redirects file. Doing it for all the sites now.

**Comment by amol-anand** [comment]
Added archive page for all geos and redirect from /archive.cfm to /archive for all geos. Good to go now.

**Comment by veejayricana** [comment]
Thank @amol-anand for adding the archive page but upon checking the count of articles that are showed is less than right? Or is this being a category that this article is on archive? 
**Legacy :**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/46846396-d28c-40b4-b0b8-71cde1d2581d)
**Migrated:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/a62f56cd-b459-40f5-8b74-8bef07ae9055)
cc: @ravkiran @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana we've added all the news list here. Is there a specific metadata that tells if the article is archived? If so, what is that? For now, we've just made this similar to `/news`

**Comment by amol-anand** [comment]
I think the current logic just only picks the top X number of articles for the initial load on the current site and then when you select year, it brings all the articles for that year. In our case, we have made it similar to /news where all articles will show up which is why the pagination shows the number you see.

**Comment by veejayricana** [comment]
Hi @ravkiran and @amol-anand, this is the response from business to archive page that I mention above,  
screenshot:![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/c0333ab3-c70b-43d7-9788-6045fb43b08c)

**Comment by amol-anand** [comment]
Closing this out for now until you hear back from the business about what they want to do with archive.
