### ISSUE TITLE
284872 - [Newsroom][Content Migration] Incomplete year selection in dropdown

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#389]
DESCRIPTION: Year drop down does not show the years displayed in legacy page.

Migrated Page:
https://tempnewsroom.accenture.de/de/subjects/diversity

Legacy Page: 
https://newsroom.accenture.de/de/subjects/diversity/

STEPS TO REPLICATE: 
Open page in a browser
Click "YEAR" dropdown and compare with contents in legacy page

ER:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/ab543ed5-d3cc-4a9d-8fce-fd1d043b50dc)

AR:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/247af21f-8562-43b0-a1d5-f8463ba4fb12)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/284872
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
in the original site, some of the years have no articles showing up. so why would we show those as options in the dropdown? the Year dropdown should only show values for whichever articles exist.

**Comment by ravkiran** [comment]
Same as #396 and #394 

@veejayricana we'll only show those years in which articles exist. In this particular case, there're articles only from 2019 and 202 only, so the only those years are shown

Please check with the business, if showing the only those years in which the articles are present, is ok.

**Comment by veejayricana** [comment]
Hi @ravkiran and @amol-anand this is teh response from business 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/7876194d-6b10-4b62-be27-a16ddc4eec37)
