### ISSUE TITLE
290360 - [Newsroom]Content Migration][MEDIUM] Code texts displaying

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#391]
Steps to Replicate:

Step1 : Navigate to page https://tempnewsroom.accenture.com/news/2018/accenture-interactive-acquires-swedish-customer-relationship-management-firm-kaplan

Live Site :  https://newsroom.accenture.com/news/accenture-interactive-acquires-swedish-customer-relationship-management-firm-kaplan.htm

Step2: Go to "copyright" section.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/18819627-0beb-4215-b5d5-4119af851eda)

Expected Result: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/9f4bf6d1-6eb9-455a-a3e6-80f3ba856742)

Actual Result: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/537f518d-ac98-4cbf-a422-00ee19438515)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/290360
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
@veejayricana please fix the content. Clearly this is one of the pages where the Metadata block is messed up at the bottom of the page. Go ahead and fix the content.

**Comment by amol-anand** [comment]
I just fixed this in the content itself. https://main--accenture-newsroom--hlxsites.hlx.live/news/2018/accenture-interactive-acquires-swedish-customer-relationship-management-firm-kaplan
