### ISSUE TITLE
291599 - [Newsroom][Content Migration] - Hero and article title mismatch

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#392]
Description: Page format difference in hero title and article title

Legacy: 
1.https://newsroom.accenture.com/news/banco-sabadell-and-accenture-team-to-transform-thebanks-technology-infrastructure.htm
2.https://newsroom.accenture.com/news/accenture-achieves-global-iso-14001-certification.htm
3.https://newsroom.accenture.com/news/accenture-and-b2bemarkets-join-forces-to-helpcompanies-source-goods-on-internet.htm
4.https://newsroom.accenture.com/news/accenture-creates-health-public-service-operating-group-to-focus-and-expand-services-to-healthcare-government-and-public-service-clients.htm
5.https://newsroom.accenture.com/news/accenture-named-one-worlds-most-ethical-companies-for-third-consecutive-year.htm

Migrated:
1.https://tempnewsroom.accenture.com/news/2000/banco-sabadell-and-accenture-team-to-transform-thebanks-technology-infrastructure
2.https://tempnewsroom.accenture.com/news/2009/accenture-achieves-global-iso-14001-certification
3.https://tempnewsroom.accenture.com/news/2000/accenture-and-b2bemarkets-join-forces-to-helpcompanies-source-goods-on-internet
4.https://tempnewsroom.accenture.com/news/2009/accenture-creates-health-public-service-operating-group-to-focus-and-expand-services-to-healthcare-government-and-public-service-clients
5.https://tempnewsroom.accenture.com/news/2010/accenture-named-one-worlds-most-ethical-companies-for-third-consecutive-year

Expected:
-Hero title is in bold, h1, 58px
-publish date is inside hero banner
-Article title font size is 16px
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/49c76360-952e-401f-b3af-732bb5c1865a)

Actual:
-Missing Hero title
-Missing publish date
-Article title font size is 65px
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/3e1da8a8-6bbc-4358-a476-aecf05ead2de)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/291599
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
We have only one style of Hero for all the pages. These articles are older articles that will now follow the new style of hero which is there for all newer articles.
