### ISSUE TITLE
292484 - [Newsroom][Content Migration] https://tempnewsroom.accenture.com/news/global-expansion-strategies-fail-to-pay-off-for-mostfinancial-services-firms-but-winners-leverage-four-key-strategies.htm - Missing News posting Hero Title

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#393]
Description of the issue:  The Title of the article is missing in the News posting Hero.  It was listed below the News posting hero and font is bigger.

Legacy page:  https://newsroom.accenture.com/news/global-expansion-strategies-fail-to-pay-off-for-mostfinancial-services-firms-but-winners-leverage-four-key-strategies.htm
Migrated:  https://tempnewsroom.accenture.com/news/global-expansion-strategies-fail-to-pay-off-for-mostfinancial-services-firms-but-winners-leverage-four-key-strategies.htm

Steps to replicate:
Access the Legacy and Migrated page.
Compare the look and feel of the page.
Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/de73ddb1-453d-497b-82fe-896e2bb18080)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/48ee46b8-149c-459d-8acc-9caca9ebe50c)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/292484
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
We have only one style of Hero for all the pages. These articles are older articles that will now follow the new style of hero which is there for all newer articles. Closing any ticket that is comparing those two things.
