### ISSUE TITLE
[296422 - Newsroom][Content Migration] Incomplete year selection in dropdown

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#394]
DESCRIPTION: Year dropdown has limited selections.

STEPS TO REPLICATE:
Open page in a browser
Click Year dropdown and compare selections with the legacy page

MIGRATED PAGE:
https://tempnewsroom.accenture.de/de/industries/konsumgter-handel

LEGACY PAGE:
https://newsroom.accenture.de/de/industries/konsumgter-handel/

ER:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/49c137ad-fad0-4397-808b-5e197edf8558)

AR:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/18858c40-66d2-4333-8f2d-2b6597512a48)

Azdo link : https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/296422
cc @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
original site has years in dropdown that have no content from what I have seen across some other pages.

**Comment by ravkiran** [comment]
Same as #396 

@veejayricana we'll only show those years in which articles exist. In this particular case, there're articles from 2022 only, so the year 2022 is only shown. 
In https://newsroom.accenture.de/de/industries/konsumgter-handel/, the articles are only from 2020 and 2022, so only those are shown in https://tempnewsroom.accenture.de/de/industries/konsumgter-handel

Please check with the business, if showing the only those years in which the articles are present, is ok.
