### ISSUE TITLE
301738 - {Newsroom][Content MIgration] Missing Hero Title

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#395]
Navigate to page url: https://tempnewsroom.accenture.com/news/2008/accenture-expands-global-delivery-network-with-opening-delivery-center-in-noida-india Live page: https://newsroom.accenture.com/news/accenture-expands-global-delivery-network-with-opening-delivery-center-in-noida-india.htm
Screenshots
ER:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/763a87fd-f4b7-4e22-a410-6798c421dffa)

AR:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/0d43e975-2c30-4729-9aac-f8fab298fb63)

Azdo link : https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/301738
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
We have only one style of Hero for all the pages. These articles are older articles that will now follow the new style of hero which is there for all newer articles. Closing any ticket that is comparing those two things.
