### ISSUE TITLE
311192- [Newsroom][Content Migration][LOW] Incomplete year selection on dropdown menu

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#396]
Steps to Reproduce:

Step1: Navigate to https://tempnewsroom.accenturebr.com/br/industries/healthcare

Live site : https://newsroom.accenturebr.com/br/industries/healthcare/

Step2: Inspect year dropdown menu

Expected Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/1d5d53c2-c133-4de1-8c79-794472342851)

Actual Result :
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/564e2456-1a77-48d0-b7b5-c799038f17bf)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/311192
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@veejayricana we'll only show those years in which articles exist. In this particular case, there're no articles from 2023, so the year 2023 isn't shown. In https://newsroom.accenturebr.com/br/industries/healthcare/, if you select 2023, its just showing the same content with out any filtering, so this isn't working anyways in the existing site. 

Please check with the business, if showing the only those years in which the articles are present, is ok.

<img width="1450" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/540237a6-45a4-42fd-9c85-533da5ef9603">
