### ISSUE TITLE
315436- [Newsroom][Content Migration] Missing Hero Text Display

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#397]
DECRIPTION: Missing Hero Text Display

Steps to Reproduce: 
Open Migrated Newsroom page https://tempnewsroom.accenture.com/news/2001/accenture-opens-two-new-offshore-development-facilities
Legacy Page: https://newsroom.accenture.com/news/accenture-opens-two-new-offshore-development-facilities.htm
Go to the hero section. Check the text display

Screenshot

Expected
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/16a3c046-3f3a-4257-ac25-2d4b5033c2ea)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/755cf937-2a91-4b20-9cf2-ce3c5bdeb66e)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/315436
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
We have only one style of Hero for all the pages. These articles are older articles that will now follow the new style of hero which is there for all newer articles.
