### ISSUE TITLE
316514 - [Newsroom][Content Migration] Missing Hero Text Display 

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#398]
Description: Missing Hero Text Display

Steps to Reproduce: 
Open Migrated Newsroom page https://tempnewsroom.accenture.com/news/2002/accenture-campaign-breaks-new-ground-for-professional-services-firms-brcenteri-am-your-idea-use-me-center
Legacy Page: https://newsroom.accenture.com/news/accenture-campaign-breaks-new-ground-for-professional-services-firms-brcenteri-am-your-idea--use-me-center.htm
Check the hero of the page

Expected:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/284c775d-2ed0-4716-8c6a-24fd72ae1058)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/e6f3d096-5a36-4eff-9c44-5bbac1b383ca)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/316514
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
We have only one style of Hero for all the pages. These articles are older articles that will now follow the new style of hero which is there for all newer articles.
