### ISSUE TITLE
319561 - [Newsroom][Content Migration] Mismatch Topic title Font Size

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#399]
Steps to Replicate: 
Open Migrated Newsroom page https://tempnewsroom.accenture.es/es/news/2023/accenture-y-microsoft-amplian-su-colaboracion
Legacy Page: https://newsroom.accenture.es/es/news/accenture-y-microsoft-amplian-su-colaboracion.htm
Check the font size of the topic title.
Screenshots:
ER:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/57551051-6682-494e-adcf-f9f4e6a6acac)

AR:
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/7c811d8a-e975-4223-9745-b9136bff3226)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/319561
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by amol-anand** [comment]
This issue doesn't exist anymore. please refresh your browser cache.
