### ISSUE TITLE
Pre Go-Live Tasks

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/accenture-newsroom#408]
Wrap up as many of the go-live tasks as possible the day before the actual go-live once confirmed. This will ensure that go-live will go smoothly with as little interruptions as possible.

https://www.aem.live/docs/go-live-checklist

- [x] Update sitemap.yaml in each geo to use the production hostname and regenerate the sitemap to reflect production hostnames (can be done before go-live)
- [x] Update sidekick config to point to prod domain (can be done just before go-live)
- [x] Update config.xlsx `host` and `cdn.prod.host` to point to production hostnames (can be done before go-live)
- [x] Update the push invalidation cdn keys in config.xlsx (can be tested after go-live but configured before go-live)
```
cdn.prod.host
cdn.prod.type
cdn.prod.distributionId
cdn.prod.accessKeyId
```
- [x] Add robots.txt to point to /sitemap.xml (during go-live)
- [x] Setup accesskey for CDN to bypass secure site on .live `access.apiKeyId`

**Comment by raymond-h-dev** [comment]
Hi @amol-anand we have finished updating the cloudfront x-forwared-host value and the host and cdn configurations in config.xlsx file(item #2 and #4). thanks

**Comment by amol-anand** [comment]
All items complete
