### ISSUE TITLE
349177 - [Newsroom] Newsfeed- Some pages not pulled when filtering by date range

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#419]
**Steps to Reproduce:** 
1. Open URL 
  **Legacy newsroom page:**
   -https://newsroom.accenture.com/subjects/acquisitions/
    **Adobe Franklin migrated page:** 
    -https://tempnewsroom.accenture.com/subjects/acquisitions?from_date=9%2f1%2f2023&to_date=10%2f26%2f2023
2. Click on Calendar filter
3. Select the date 01 Sept 2023 - 26 Oct 2023
**Expected (Legacy Newsroom Page):** All articles of  01 Sept 2023 - 26 Oct 2023 should be visible
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/1664a650-1469-4e86-9614-bbae10a51360)

**Actual (Migrated Page):** Only 3 pages were pulled. Understood that the latest pages might not be pulled as these are not yet migrated. However, for the article dated Sept 5 it's not being pulled as well. Please check if any issues. 
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/d7b9c6e3-5ee7-46aa-b80c-09d06f675616)

Another issue is inconsistency with the results, please check if this is a caching issue:
**Result 1:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/92af6c47-77d8-4856-9363-0e8e27703b18)

**Result 2**:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/81404414-62ac-440e-83ff-dd4d2361470a)

**Result 3:**
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/a866b361-d39f-4c79-b935-74bc418b8aac)

Azdo Link - https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/349177
CC: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@jjjaspher The Franklin imported version of the [Sept 5th article](https://newsroom.accenture.com/news/accenture-acquires-leading-digital-healthcare-consultancy-nautilus.htm) doesn't have the acquisitions tag, most likely this was added later, so it didn't come into when we run the import. I've just reimported this its showing the acquisitions tag, now showing 4 articles. The import was last done around Oct 18th, all the articles after this date will be imported on Nov 6th

I'm not able to reproduce the inconsistent results you've shared. The one possibility could be you've run this when we're reindexing. If you are still seeing this issue, please record a video with your dev tools open with Network tab visible in the chrome
