### ISSUE TITLE
[A11y] Calendar picker has no discernable text

### ISSUE THREAD

**Issue by michaelktiufb** [hlxsites/accenture-newsroom#420]
1. Navigate to: https://tempnewsroom.accenture.com/
2. Check the Calendar filter field

ER: ara-label is present with the value like "Select a date"
AR:  aria-label was not present

To solve this problem, you need to fix at least (1) of the following:
- Element has a value attribute and the value attribute is empty
- Element has an empty value attribute
- aria-label attribute does not exist or is empty
- aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
- Element has no title attribute
- Element's default semantics were not overridden with role="none" or role="presentation"

**Comment by ravkiran** [comment]
@michaelktiufb I don't find any aria-label in the existing site, can you please share a screenshot where you see the aria attribute?

<img width="1493" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/41cb4b79-f0eb-42d0-acf8-03a8d00ceb46">
