### ISSUE TITLE
index page is showing only 100 pages, update the count using total in the json

### ISSUE THREAD

**Issue by ravkiran** [hlxsites/accenture-newsroom#45]
Home page is showing only 100 pages, even though there're more than that
<img width="1298" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/614706be-6d94-4ecc-a60f-8e175f443393">

This is due to using limit =1000 for newslist block. We can't afford to load all the query-index at the same time, so load the basic query index with right limit and offset so that we can render the view fast. Read the total value from the query-index.json and show the number of pages accordingly.

**Comment by amol-anand** [comment]
It would make sense to handle it differently when when we have an offset. so when we are on page 2, we will see pagination until 101 for example. No one should have to go to more than a page anyways for search results.

**Comment by amol-anand** [comment]
Doing something like this -> https://main--accenture-newsroom--hlxsites.hlx.page/query-index.json?offset=10&limit=10
will give you the 10 results you need to see on the page while also giving you the total (2442 currently) to build out the pagination page numbers. 

That way you only ever have to pull in 10 (or however many articles we need to show in one page) at a time while also building out the pagination to the max there is in the document.

**Comment by ravkiran** [comment]
>Doing something like this -> https://main--accenture-newsroom--hlxsites.hlx.page/query-index.json?offset=10&limit=10
will give you the 10 results you need to see on the page while also giving you the total (2442 currently) to build out the pagination page numbers.

Ideally yes, but we'll have to filter out certain pages like `/industries/`, `/`, `/subjects/` so we will need to ask for more and then filter on the clientside. But I'll be implementing this with offset and limit only but a little higher limit than 10.
