### ISSUE TITLE
59683 - [Newsroom] Newsfeed- Error message is not visible when search without keyword

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#51]
Priority 2 - High

Steps to Reproduce: 
1. Open URL 
 **Legacy newsroom page:**
   - Homepage: https://newsroom.accenture.com/
 
   **Adobe Franklin migrated page:** 
   - Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/
   
2. Click on Search icon
3. Redirect to https://main--accenture-newsroom--hlxsites.hlx.live/search
Actual (Migrated Page): No error message visible in search page
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/cf113a48-50dd-4fe6-8946-dd6067dcbb3c)

Expected (Legacy Newsroom Page): Error message with back cta should be visible
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/72cc951d-8714-4421-96f9-e58b62623eac)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59683
CC: @ravkiran  @amol-anand  @raymond-pogi

**Comment by ravkiran** [comment]
@jjjaspher moving the question asked in #92 to here

do we need to show the error when the user didn't enter any search? The search seems pretty intuitive to enter the keywords. If the user don't enter any keywords, there won't be any result.

**Comment by jjjaspher** [comment]
> @jjjaspher moving the question asked in #92 to here
> 
> do we need to show the error when the user didn't enter any search? The search seems pretty intuitive to enter the keywords. If the user don't enter any keywords, there won't be any result.

I'll cascade it to the team and will get back to you for their decision

**Comment by jjjaspher** [comment]
> > @jjjaspher moving the question asked in #92 to here
> > do we need to show the error when the user didn't enter any search? The search seems pretty intuitive to enter the keywords. If the user don't enter any keywords, there won't be any result.
> 
> I'll cascade it to the team and will get back to you for their decision

Hi @ravkiran , After consulting with our Product Owner (PO), it has been determined that displaying an error message is essential. This message serves as a clear indicator to users that they haven't entered any keywords for their search.

**Comment by jjjaspher** [comment]
I think this bug https://github.com/hlxsites/accenture-newsroom/issues/103 is related as well

**Comment by jjjaspher** [comment]
Hi @ravkiran, our scrum master has inquired about the status of the mentioned issue. Could you please provide an update when convenient? Thank you!

**Comment by Jaykaaa** [comment]
hello @ravkiran a gentle follow up on this please. Thank you.

**Comment by Jaykaaa** [comment]
hello @ravkiran do you have an update on this? Thanks.
