### ISSUE TITLE
59782 - [Newsroom] Newsfeed- Sorting not working on search results by a date range

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#52]
**Priority 2 - High**

**Steps to Reproduce:** 
1. Open URL 
Legacy newsroom page:
Homepage: https://newsroom.accenture.com/
Adobe Franklin migrated page: 
Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/
2. Click on Calender filter
3. Select the date 26 july 2023 - 27 july 2023
**Expected (Legacy Newsroom Page): All articles of 26 july 2023 - 27 july 2023 should be visible**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/8fe6825c-ea05-43dd-a012-dac9dba193a6)

**Actual (Migrated Page): Only 26july 2023 date article is visble and is not arrange alphabetical.**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/75a7d594-0d57-4be4-9044-a3e5743b0db2)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59782
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by jjjaspher** [comment]
Alphabetical order is invalid, the only issue is the mismatch of result between legacy and migrated pages
