### ISSUE TITLE
59852 - Dropdown arrow instead of calendar filter in small device

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#53]
**Priority 2 - High**

**Steps to Reproduce:** 
1. Open URL https://main--accenture-newsroom--hlxsites.hlx.live/
1. Right click and open dev tool
1. Navigate to newsfeed
**Actual: Dropdown arrow is visible**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/55715c6c-08ef-44bb-b974-eec9c5830aca)

**Expected: Calendar Filter should be visible**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/006f5b65-5327-4adb-8274-e9ab4d25d462)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59852
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by jjjaspher** [comment]
Closing the bug, as the issue can't be replicated.
