### ISSUE TITLE
59214 - [Newsroom] News Posting Hero - Breadcrumb alignment (Browser, Tablet and Mobile View)

### ISSUE THREAD

**Issue by jjjaspher** [hlxsites/accenture-newsroom#54]
Severity 3 - Medium
Description of the issue:  
Breadcrumb is not aligned with the content on Browser View, Tablet View and Mobile View.

Legacy Page:  https://newsroom.accenture.com/news/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture.htm
Migrated Page:  https://main--accenture-newsroom--hlxsites.hlx.live/news/coca-cola-bottlers-japan-and-accenture-to-establish-joint-venture

Steps:
1. Access the Newsroom Legacy and Migrated page.
2. Verify elements for Hero in both domains
Expected Result:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/908befa1-b019-48d9-8837-64795f3846b1)

Actual:
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/84fadc13-f2e8-47a5-ad07-5fd8fd129b25)

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59214
CC: @ravkiran  @raymond-pogi  @amol-anand

**Comment by veejayricana** [comment]
Hello @amol-anand and @ravkiran good day! Re-opening this bug for the same issue encountered on JP, ES geo.  Thank you!
Legacy page:  
[JP] - https://newsroom.accenture.jp/jp/news/release-20230803.htm
[ES] - https://newsroom.accenture.es/es/news/accenture-intel-sulubaai-environmental-foundation-inteligencia-artificial.htm
Migrated page:
[JP] - https://main--accenture-newsroom-jp--hlxsites.hlx.page/jp/news/2023/release-20230803
[ES] - https://main--accenture-newsroom-es--hlxsites.hlx.page/es/news/accenture-intel-sulubaai-environmental-foundation-inteligencia-artificial

Expected:
[JP]
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/4830ad54-053b-4465-8317-378172376994)
[ES]
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/803bd32c-ce63-47ff-9041-0588781da3f5)
Actual:
[JP]
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/1d93d5eb-b5b4-48e2-b1e5-ff177cc2e0dc)
[ES]
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/40f44fcb-f595-458f-b256-2556b0060e4a)

Azdo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59214 
cc : @jjjaspher @raymond-h-dev

**Comment by veejayricana** [comment]
hi @ravkiran, this function fialed in other local geo example jp and es.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/636d6285-a9a9-4cb7-a977-7e18d4a3a541)
It failed to add abstract class thus these styling dont work.  
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/1fcb4c23-b220-4b36-9e63-df9ebe563914)

**Comment by ravkiran** [comment]
@veejayricana yes, looks like for these pages 
https://main--accenture-newsroom-es--hlxsites.hlx.page/es/news/2020/accenture-intel-sulubaai-environmental-foundation-inteligencia-artificial
https://main--accenture-newsroom-jp--hlxsites.hlx.page/jp/news/2023/release-20230803
abstract isn't found, so its showing the content little weird. 
In these case we need to fix this manually by going to the document and adding `---` after the abstract and saving --> preview --> publish, that should fix the issue. Can you please take care of that?
We've created https://github.com/hlxsites/accenture-newsroom/issues/210 to take care of all the missing abstract documents. For now, you can fix these manually and resolve this issue.

**Comment by veejayricana** [comment]
hi @ravkiran i already add --- in the document but still there is no abstract in the html class..
Test document: [Test Abstract](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B3E192EC3-DDAF-44B3-B48D-1B10BB16CB4D%7D&file=[accenture-intel-sulubaai-environmental-foundation-inteligencia-artificial.docx](https://ts.accenture.com/:w:/r/sites/AdobePlatformAuthor/newsroom/_layouts/15/Doc.aspx?sourcedoc=%7B3E192EC3-DDAF-44B3-B48D-1B10BB16CB4D%7D&file=accenture-intel-sulubaai-environmental-foundation-inteligencia-artificial.docx&action=default&mobileredirect=true)&action=default&mobileredirect=true)

cc: @amol-anand

**Comment by ravkiran** [comment]
@veejayricana 
We've made the change to the abstract finding in https://github.com/hlxsites/accenture-newsroom/pull/339, the first section in article will be considered as abstract section, so there's no regex check. The above document is't available, please validate from your side.
