### ISSUE TITLE
60426 - [Newsroom] Common Modules - Content and Links - Missing link on text

### ISSUE THREAD

**Issue by veejayricana** [hlxsites/accenture-newsroom#55]
**Priority 2 - High**

**Steps to Reproduce:**
1. Navigate to migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/news/accenture-completes-acquisition-of-anser-advisory
Legacy Page: https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
2. Look for the phrase "first announce" on the second paragraph.
3. Click the link.
**Expected: The text has a link and navigates to linked page when clicked.**
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/2fdea448-b349-4280-a4ca-a84d54b2c746)

**Actual: Text has no linked URL.**

![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/07503b49-89dc-4576-b932-908b47502249)

Note: Text is authored correctly on the document, but appears without link in the preview/migrated page.

Screenshot: 
![image](https://github.com/hlxsites/accenture-newsroom/assets/143703040/569ca268-6082-47f9-abc9-ca6c5d15937d)
Document link: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B555F1972-82C3-4041-A943-2C8E4CAD0E81%7D&file=accenture-completes-acquisition-of-anser-advisory.docx&action=default&mobileredirect=true

Azdo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/60426
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by jjjaspher** [comment]
.

**Comment by veejayricana** [comment]
@jjjaspher  ..?

**Comment by veejayricana** [comment]
h

**Comment by veejayricana** [comment]
Upon checking, this bug can be fix via authoring and currently waiting for the response from my PO regard the link path because in legacy/old page the year is not visible.

Legacy: https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
Migrated: https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-anser-advisory

cc: @raymond-h-dev @ravkiran @amol-anand

**Comment by amol-anand** [comment]
Just keep in mind we would add redirects from old links (without year) to new (with year) as well.

**Comment by amol-anand** [comment]
is this still an issue?

**Comment by ravkiran** [comment]
@veejayricana earlier the links doesn't seem to be styled, now the links are being styled property. 
<img width="1119" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/9177ee03-e75e-4fb8-90a0-1d80f0bfb9b4">
But, the url will be giving 404 now, as this is legacy url. Once we add all the redirects as @amol-anand is saying, then this issue will be fixed.

**Comment by jjjaspher** [comment]
Hi @ravkiran, our scrum master has inquired about the status of the mentioned issue. Could you please provide an update when convenient? Thank you!

**Comment by Jaykaaa** [comment]
hello @ravkiran  a gentle follow up on this please. Thank you.

**Comment by ravkiran** [comment]
We've just moved from Adobe sharepoint to Accenture sharepoint today. We need to run one last import, then we'll add the redirects. @amol-anand can you please share, when we'll be able to add the redirects?

**Comment by amol-anand** [comment]
i've added the redirects in the adobe sharepoint already for the language sites. not for the EN site yet. going to do it after the next import. keep this open and test it after the next import.

**Comment by Jaykaaa** [comment]
hello @amol-anand  Just wanted to ask if we have an update on this? Thanks.

**Comment by Jaykaaa** [comment]
Hello @amol-anand  do we have an update on this issue?

**Comment by ravkiran** [comment]
redirects will be added tomorrow, once done, we'll close this ticket, then you can validate

**Comment by Jaykaaa** [comment]
hello @ravkiran  Are we done with redirect? Thanks.

**Comment by ravkiran** [comment]
@Jaykaaa redirects are complete.
validated on https://tempnewsroom.accenture.com/news/accenture-announces-intent-to-acquire-optimind-a-consulting-firm-specializing-in-financial-services-insurance-and-compliance-risk-management.htm
and https://tempnewsroom.accenture.com/news/accenture-to-acquire-anser-advisory-to-expand-capital-project-capabilties.htm
Please check from your side as well.

**Comment by Jaykaaa** [comment]
Thank you @ravkiran
