### ISSUE TITLE
60434- [Newsroom] Common Modules- Global Navigation/Header- Secondary link with long text not shifted to second line

### ISSUE THREAD

**Issue by Rashi24** [hlxsites/accenture-newsroom#65]
Priority: 3 medium

**Steps to Reproduce:**
1. Open URL 
  **Legacy newsroom page:**
  Homepage: https://newsroom.accenture.com/
  **Adobe Franklin migrated page:** 
  Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/
2. Click on Industry in the global header
3. Check the secondary link long text

**Actual (Migrated Page):** Secondary link with long text not shifted to second line
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/ea868d15-1ede-4664-b47e-547c4f1c8c21)

**Expected (Legacy Newsroom Page):** Secondary link with long text should shifted to the second line
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/f5e1b633-4e4a-41b9-b936-7445806edb0a)

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/60434
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by zozo-j** [comment]
- [ ] Code Build
- [ ] Smoke Testing - Feature Branch
- [ ] Ready for PR Approval
