### ISSUE TITLE
59628- [Newsroom] Common Modules- Global Navigation/Header- Primary link text is not changed to bold when clicked

### ISSUE THREAD

**Issue by Rashi24** [hlxsites/accenture-newsroom#66]
**Steps to Reproduce:** 
1. Open URL 
  **Legacy newsroom page:**
  Homepage: https://newsroom.accenture.com/
  **Adobe Franklin migrated page:** 
  Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/
2. In Global Navigation/Header, click on primary link

Expected (Legacy Newsroom Page): Link should be changed to bold. 
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/4bd34778-0666-4da1-9cc0-31c6bfc45e58)

Actual (Migrated Page): Link text not changed to bold.
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/0a3c15f7-1290-47a3-b584-279eef22a262)

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59628
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by zozo-j** [comment]
- [ ] Code Build
- [ ] Smoke Testing - Feature Branch
- [ ] Ready for PR Approval
