### ISSUE TITLE
60633 - [Newsroom] Common Modules - Content and Links - Incorrect alignment of special character on all pages

### ISSUE THREAD

**Issue by inygojay** [hlxsites/accenture-newsroom#69]
Severity: 3 - Medium

**Steps to Reproduce:**

1. Navigate to migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/news/accenture-completes-acquisition-of-anser-advisory
2. Legacy Page: https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
3. Navigate to last part of the article, before the contacts part.

**Expected: "###" is center aligned**
![image](https://github.com/hlxsites/accenture-newsroom/assets/144990112/ab501fb3-9688-438d-a633-7a4d1e310704)

**Actual: "###" is left aligned**
![image](https://github.com/hlxsites/accenture-newsroom/assets/144990112/fd3ce933-41c1-4653-9010-81da358bbf4f)

AzDo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/60633?src=WorkItemMention&src-action=artifact_link

cc: @ravkiran @amol-anand @raymond-pogi

**Comment by jjjaspher** [comment]
reopening the issue, need to consider the .section with .video-container
https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-song-wins-dan-wieden-titanium-grand-prix-for-tuvalu-the-first-digital-nation
![image](https://github.com/hlxsites/accenture-newsroom/assets/142872664/7723f732-68b9-42f1-bbf6-77d90cfafeeb)

**Comment by jjjaspher** [comment]
reopening the issue, need to update the querySelector for article
