### ISSUE TITLE
59664- [Newsroom] Newsfeed- Divider is missing below Search and Calendar Filter

### ISSUE THREAD

**Issue by Rashi24** [hlxsites/accenture-newsroom#70]
**Priority**: 3 - Medium
**Steps to Reproduce:** 
1. Open URL 
**Legacy newsroom page:**
Homepage: https://newsroom.accenture.com/
**Adobe Franklin migrated page:** 
Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/
2. Navigate to the newsfeed section
**Actual (Migrated Page):** Search and Calendar Filter is in box 
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/d5b24470-3a50-4957-b662-f2d5fb41ca79)

**Expected(Legacy Newsroom Page):** Divider below the Search and Calendar Filter
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/f9f46098-4db3-4394-8408-9cfdd580112f)

Note: Issue exists in Small and Extra small devices.

Azdo Link-https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59664
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by zozo-j** [comment]
- [ ] Code Build
- [ ] Smoke Testing - Feature Branch
- [ ] For PR Approval

**Comment by amol-anand** [comment]
This looks like it was fixed last month. please confirm
