### ISSUE TITLE
59795- [Newsroom] Newsfeed- On hover, Read More cta color is not changing in news card

### ISSUE THREAD

**Issue by Rashi24** [hlxsites/accenture-newsroom#71]
**Priority**: 3 - Medium
**Steps to Reproduce:**
1. Open URL 
**Legacy newsroom page:**
Homepage: https://newsroom.accenture.com/
**Adobe Franklin migrated page:** 
Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/
2. Hover over Read More cta
**Expected (Legacy Newsroom Page):** Read more cta color change to dark blue #008800
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/79f472f5-7999-40a5-9575-a51aa5c1c36a)

**Actual (Migrated Page):** Read More cta color is not changed
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/c1dd37d8-dcce-4616-8c12-ac14c6789831)

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59795
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by ravkiran** [comment]
fixed in https://github.com/hlxsites/accenture-newsroom/pull/114
