### ISSUE TITLE
59834- [Newsroom] Newsfeed- News Card title font size is 18px instead of 20px

### ISSUE THREAD

**Issue by Rashi24** [hlxsites/accenture-newsroom#72]
**Steps to Reproduce:**
1. Open URL 
**Legacy newsroom page:**
Homepage: https://newsroom.accenture.com/
**Adobe Franklin migrated page:** 
Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/

2. Open dev tools

**Actual (Migrated Page):**
Title:
Font size: 18px
Line height: 21.6px

Description
Font size: 14px
Line height: 25.6px
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/e507a26e-f37b-447b-9f69-d982b229cd98)

**Expected (Legacy Newsroom Page):**
Title:
Font size: 20px
Line height: 24px

Description
Font size: 16px
Line height: 25.6px

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59834
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by ravkiran** [comment]
fixed in https://github.com/hlxsites/accenture-newsroom/pull/114
