### ISSUE TITLE
59855- [Newsroom] Newsfeed- Single news card visible in row instead of two cards  for small devices

### ISSUE THREAD

**Issue by Rashi24** [hlxsites/accenture-newsroom#77]
Priority: 3 - Medium

**Steps to Reproduce:** 
1. Open URL 
**Legacy newsroom page:**
Homepage: https://newsroom.accenture.com/
**Adobe Franklin migrated page:** 
2. Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/
3. Right click and open dev tool
4. Navigate to newsfeed

**Actual (Migrated Page):** Single news card visible in row
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/431d51b9-0a84-4066-ade3-68a5a18faad6)

**Expected (Legacy Newsroom Page):** Two news cards should be visible in a row
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/dc892eff-9a94-4ce4-a85d-404486ec43c5)

**Device | iPad 5th | | Browser | Tablet_safari | | Operating System | iOS 15.0 | | Resolution | 1536 x 2048 px | | Screen size | 9.7 in - 5.8 x 7.8 in | | Viewport | 768 x 954 px | | Aspect Ratio | 4 : 3 |**

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59855
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by jjjaspher** [comment]
This is no longer replicated, Closing the bug now.
