### ISSUE TITLE
59870- [Newsroom] Newsfeed- Extra space between article text and read more cta for mobile devices

### ISSUE THREAD

**Issue by Rashi24** [hlxsites/accenture-newsroom#78]
Priority: 3 - Medium

**Steps to Reproduce:** 
1. Open URL 
Legacy newsroom page:
Homepage: https://newsroom.accenture.com/
Adobe Franklin migrated page: 
Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/
2. Open dev tool
3. View in a mobile device

**Actual (Migrated Page):** Extra space between article text and read more cta 
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/39f2d934-9ec5-449f-8fd6-ba4ed5935317)

**Expected (Legacy Newsroom Page):** Space between article text and read more cta is 20px
![image](https://github.com/hlxsites/accenture-newsroom/assets/47206503/bb3eb484-e221-4c5f-bca6-2dbd8125ff1e)

**| Device | Samsung Galaxy S22 | | Browser | Mobile_chrome | | Operating System | Android 12.0 | | Resolution | 1080x2340 px | | Screen size | 6.1 in - 2.56 x 5.54 in | | Viewport | 360 x 649 px | | Aspect Ratio | 19.5 : 9 |**

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59870
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by ravkiran** [comment]
fixed in https://github.com/hlxsites/accenture-newsroom/pull/114
