### ISSUE TITLE
67400[Newsroom] Common Modules -News Posting Article-Space on the right of the para and share component is more on legacy page then on the franklin page.

### ISSUE THREAD

**Issue by EkanshGitBugs** [hlxsites/accenture-newsroom#81]
1.open both the below URL legacy and franklin one

Sample Reference/s:
Legacy newsroom page:
https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
Adobe Franklin migrated page: 
https://main--accenture-newsroom--hlxsites.hlx.live/news/2023/accenture-completes-acquisition-of-anser-advisory

2.Verify the space between the para and the right side share component and tags below is less on legacy page than on franklin page.

Legacy page
On the para section there is no left and right padding give.
There is on 30 pixels left padding on the share component if you inspect and check.

Franklin page
For the para section there is 32 pixels padding on the right side 
and also 32 pixels padding on the left side of share component.

So, fix as per the legacy page.

Expected : it should be same as legacy page

Note: Do inspect and check.

![Space on the right of the para and share component is more on legacy page then on the franklin page](https://github.com/hlxsites/accenture-newsroom/assets/144997178/f3e6c456-eefc-472e-9e81-910de4e63e33)

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/67400
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by jjjaspher** [comment]
this has wrong Azdo ID.
Updating from 63679 to 67400.

**Comment by ravkiran** [comment]
fixed in https://github.com/hlxsites/accenture-newsroom/pull/164
