### ISSUE TITLE
67081 - [Newsroom] Newsfeed - Calendar year filter reset issue

### ISSUE THREAD

**Issue by Saiveeru** [hlxsites/accenture-newsroom#84]
**Severity 3 - Medium**

Steps to Reproduce: 

In the Newsfeed, Upon selecting the date range in date filter after selecting the year in the calendar year filter. Both the filters are appearing as selected with some value.

Migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/industries/systems-integration-technology

Legacy page: https://newsroom.accenture.com/industries/systems-integration-technology/

**1**. Select the year in calendar year filter(The results are displayed of the respective year).
**2**. Now select the date from the calendar date filter(The results are displayed within the provided date range).
**3**. Both the filters are appearing as selected in the migrated page(Please refer to the snippets in the actual section).

**Expected:**

**Image1:** ![image](https://github.com/hlxsites/accenture-newsroom/assets/49959047/e8832b87-b4d9-47b0-bb08-bc5ed0fdf907)

**Image2:** ![image](https://github.com/hlxsites/accenture-newsroom/assets/49959047/878c4f49-97b3-4318-9eb3-73688fc0b4ea)

**Actual:**

**Image1:** ![image](https://github.com/hlxsites/accenture-newsroom/assets/49959047/bbeac138-aec2-414f-8538-a4df6f0822c6)

**Image2:** ![image](https://github.com/hlxsites/accenture-newsroom/assets/49959047/82ab94da-2754-4dd1-b417-72ed9b58d2c2)

**Azdo link**: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/67081

CC: @ravkiran @amol-anand @raymond-pogi

**Comment by ravkiran** [comment]
this is working fine, so resolving this.
