### ISSUE TITLE
61934[Newsroom] Common Modules - Hero - Newsroom heading is more towards right side

### ISSUE THREAD

**Issue by EkanshGitBugs** [hlxsites/accenture-newsroom#85]
Priority: 3 medium

Steps to Reproduce: | Analysis & Proposed Solution: | Location of the Element:

1.open both the below URL legacy and franklin one

Legacy newsroom page:
https://newsroom.accenture.com/
Adobe Franklin migrated page: 
https://main--accenture-newsroom--hlxsites.hlx.live/

2. On the franklin migrated page verify the newsroom heading should be left aligned with hero card

Actual: It is not aligned coming more towards the right side
Expected: It should be aligned to left as per the card and legacy page

Browser tested:
![1](https://github.com/hlxsites/accenture-newsroom/assets/144997178/22b4f4e4-0198-49be-9a0c-bbc66f7a1f4b)

Google Chrome, Safari and Microsoft Edge

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/61934
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by zozo-j** [comment]
duplicate from #106
