### ISSUE TITLE
61537[Newsroom] Common Modules - Hero - Space on the left of the hero is more on the legacy as compared to franklin page.

### ISSUE THREAD

**Issue by EkanshGitBugs** [hlxsites/accenture-newsroom#87]
Steps to Reproduce: | Analysis & Proposed Solution: | Location of the Element:

1.open both the below URL legacy and franklin one

Legacy newsroom page:
https://newsroom.accenture.com/
Adobe Franklin migrated page: 
https://main--accenture-newsroom--hlxsites.hlx.live/

2. On the franklin migrated page verify the hero card left spacing; it is less in comparison to the legacy page.

Expected: Make the space adjustment as per the legacy page.

Browser tested:
chrome edge safari

![image](https://github.com/hlxsites/accenture-newsroom/assets/144997178/f6363a20-50e3-424f-8676-d7868f9cf6b0)

Azdo link:https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/61537
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by zozo-j** [comment]
duplicate issue from #107
