### ISSUE TITLE
63679 [Newsroom] Common Modules -News Posting Article-No tool tip appears while hover on the links on legacy page while appears for franklin page.

### ISSUE THREAD

**Issue by EkanshGitBugs** [hlxsites/accenture-newsroom#89]
Priority: 3 medium

Steps to Reproduce: | Analysis & Proposed Solution: | Location of the Element:

1.open both the below URL legacy and franklin one

Legacy newsroom page:
https://newsroom.accenture.com/news/accenture-completes-acquisition-of-anser-advisory.htm
Adobe Franklin migrated page: 
https://main--accenture-newsroom--hlxsites.hlx.live/news/accenture-completes-acquisition-of-anser-advisory

2.Hover over any inline link on the article section for both 

3.Observe that while hovering tool tip is not coming on the legacy while coming for the franklin.

![image](https://github.com/hlxsites/accenture-newsroom/assets/144997178/4f1451e5-29f3-440f-9294-6a191887d772)

Azdo link:https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/63679
cc: @ravkiran @amol-anand @raymond-pogi

**Comment by jjjaspher** [comment]
it has duplicate issue, closing the bug, 
https://github.com/hlxsites/accenture-newsroom/issues/81

**Comment by EkanshGitBugs** [comment]
> it has duplicate issue, closing the bug, #81
Hi @jjjaspher  this is not duplicate bug.
this is different bug related to tool tip while hovering the links on legacy page..
