### ISSUE TITLE
73335 [Newsroom] Search - When no keyword is entered search is not redirected to error page

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#92]
Priority: 2 - High

Steps to Reproduce:

1.Consider the legacy page: https://newsroom.accenture.com/search.cfm 
and Migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/search?q=
2.Directly hit the 'search' CTA / don't enter any value in search field and perform search 

Expected Result: As per the legacy search page: 
When no keyword is entered, it should redirect to https://newsroom.accenture.com/search_results.cfm with the error message below and CTA (arrow left icon, "Back" text) pointing to https://newsroom.accenture.com/search.cfm

![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/06b1c1de-33ca-4eb6-a099-193daa2e2def)

Actual Result: In the Migrated page the user is redirected to the search page only without any error message getting displayed.
![image](https://github.com/hlxsites/accenture-newsroom/assets/143692161/6dcbaf8a-4821-4da1-8cdf-ebd54cf89530)

AzDo Link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/73335/
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
@zozo-j do we need to show the error when the user didn't enter any search? The search seems pretty intuitive to enter the keywords. If the user don't enter any keywords, there won't be any result.

**Comment by jjjaspher** [comment]
Closing the bug, has duplicate 
https://github.com/hlxsites/accenture-newsroom/issues/51
