### ISSUE TITLE
73342 [Newsroom] Search - Articles obtained in results open in same tab 

### ISSUE THREAD

**Issue by zozo-j** [hlxsites/accenture-newsroom#94]
Priority: 3 - Medium

Steps to Reproduce:

1.Consider the legacy page: https://newsroom.accenture.com/search.cfm 
and Migrated page: https://main--accenture-newsroom--hlxsites.hlx.live/search?q=
2.Perform search with a valid keyword 
3.Click on any of the article obtained after search 

Expected Result:
In legacy site the articles open in new tab 

Actual Result: In franklin migrated site, articles open in same tab.

AzDo link: https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/73342/
cc: @ravkiran @amol-anand @raymond-h-dev

**Comment by ravkiran** [comment]
fixed in https://github.com/hlxsites/accenture-newsroom/pull/115
